"""gen_c.py -- the deterministic C backend of the Zen bootstrapper.

`bootstrap/CONTRACT.md` is the frozen interface; this file consumes the AST
described there and emits C99.  It imports `ast.py`, `modules.py` and
`sema.py` and never `cst.py`.

-------------------------------------------------------------------- determinism

Binding, from CONTRACT.md and `tests/determinism/README.md`.  Every rule below
is a property of the code rather than a thing to look for later:

* every emitted list is sorted by its mangled C name, or produced by a walk
  over a source-ordered tuple.  A dict is a lookup structure here, never an
  emission order; `sorted()` is called at every emission site.
* no pointer, address, `id()`, timestamp, environment variable, locale or
  absolute path reaches the output.  Positions are literal strings taken from
  the AST, so `__FILE__` is never emitted either.
* temporaries are numbered per function by the deterministic traversal that
  emits them, and the counter is reset at every function.
* a monomorphised instance's name is a pure function of the type: it is the
  type's own encoding (`tcode` below), so two instantiations of the same type
  from different modules produce one name regardless of which was seen first,
  and no counter takes part.
* nothing is emitted from a `set`; sets are converted with `sorted()` at use.

-------------------------------------------------------------------- mangling

Two prefixes, and every identifier in the output is under one of them:

    zu_   derived from a user name
    zg_   generated by the compiler (temporaries, helpers, the runtime)

Neither starts with an underscore, so neither is reserved to the C
implementation by C11 7.1.3, and `zu_` cannot produce `zg_`, so the reserved
prefix is unreachable by any mangled user name.  Because *every* user
identifier is mangled, no C keyword, no standard-header macro and no reserved
identifier can ever be emitted from user source -- which is decision 4 of
PLAN.md 0.4 handled as an identifier *class* rather than as a keyword list.
The single exception is the C entry point `main`, which the C standard fixes.

Components are length-prefixed, so concatenation is unambiguous:

    comp  := <decimal byte length> <bytes>
    list  := <decimal count> "_" comp*        (a count always ends with "_",
                                               a component never does)

A length is read as the maximal digit run; a Zen identifier can never start
with a digit, so the parse is unique.  `alpha` + `beta_gamma` encodes as
`2_5alpha10beta_gamma` and `alpha_beta` + `gamma` as `2_10alpha_beta5gamma`:
the collision that naive `_` joining has, closed by construction.

Symbols, by site (the seven of PLAN.md 0.4 decision 3, plus module values):

    type / instance   zu_ t <path> [I <args>]
    function          zu_ f <path> [O <param types>] [I <type args>]
    enum constant     zu_ e <path-of-enum + variant>
    struct member     zu_ m <comp>
    local / parameter zu_ l <comp> ["_" <n>]
    module value      zu_ v <path>
    struct tag        the same string as the typedef (C tags are a separate
                      namespace, so `typedef struct X X;` is legal and keeps
                      the emitted C readable)
    label             zg_ ... (generated, never user-derived)

Type arguments render through `tcode`, a pure function of the type:

    b <comp>                  primitive            i32   -> b3i32
    t <path> [I <n> "_" ...]  nominal type         Box<i32> in gamma ->
                                                   t2_5gamma3BoxI1_b3i32
    p <tcode>                 Ptr<T>
    a <count> "_" <tcode>     [T, N]
    f <ret> <n> "_" <tcode>*  function type
    u <n> "_" <tcode>*        union, members sorted so `A|B` == `B|A`
    z                         ()
    q                         unresolved (a diagnostic is raised with it)

The tag letters are lowercase and `I` is uppercase, so no tag can be mistaken
for the start of a component; the encoding is injective, so distinct types
never share a name and a user-written `Pair_i32_i32` can never collide with
`Pair<i32, i32>`.

-------------------------------------------------------------------- the failure model

DESIGN.md: signed overflow is undefined behaviour in C, so this file never
emits `a + b` and inspects the result.  Every checked operation goes through a
`zg_` helper that tests *before* the operation, using `__builtin_*_overflow`
where the compiler has it and an explicit range test where it does not.  A
trap prints `file:line:col: trap: <what>` to stderr and exits 134; the
position is the operator token, resolved by `OperatorSpans` below.

-------------------------------------------------------------------- what sema owns

gen_c asks `sema` for what it cannot know, and degrades to its own resolution
when a query is absent, so that this file compiles against a partial sema:

    sema.type_of(expr)            -> a Type node, or None
    sema.resolve(expr)            -> the declaration a Path/Member names
    sema.defs_of(name, module)    -> declarations bound to a name

All three are optional.  Anything gen_c cannot resolve becomes a `Diag`
(collected, never raised) rather than a guess.
"""

from __future__ import annotations

import os
import re

# ---------------------------------------------------------------------------
# imports of the modules above this one.  Both spellings are supported because
# `bootstrap/` is run as a directory of scripts (sys.path[0] is bootstrap/) and
# may also be imported as a package.
# ---------------------------------------------------------------------------

if __package__:
    from . import ast as zast  # type: ignore
else:  # pragma: no cover - script layout
    import ast as zast  # type: ignore  # bootstrap/ast.py, never the stdlib one

try:
    if __package__:
        from . import sema as zsema  # type: ignore  # noqa: F401
    else:  # pragma: no cover
        import sema as zsema  # type: ignore  # noqa: F401
except ImportError:  # pragma: no cover - sema is optional at this layer
    zsema = None

try:
    if __package__:
        from . import modules as zmodules  # type: ignore  # noqa: F401
    else:  # pragma: no cover
        import modules as zmodules  # type: ignore  # noqa: F401
except ImportError:  # pragma: no cover
    zmodules = None


C_STANDARD = "C99 (ISO/IEC 9899:1999)"

USR = "zu_"
GEN = "zg_"

MAX_INSTANCES = 4096  # infinite monomorphisation stops here, with a diagnostic
MAX_EXPR_DEPTH = 24  # deeper than this spills to a temporary, per TESTING.md


# ---------------------------------------------------------------------------
# node access
#
# Dispatch is on the class *name* and fields are read with getattr, so gen_c
# survives the frozen dataclasses gaining fields and never needs an isinstance
# against a class it did not import.
# ---------------------------------------------------------------------------


def kind(node):
    return type(node).__name__


def f(node, name, default=None):
    return getattr(node, name, default)


def _diag(span, message, notes=()):
    Diag = getattr(zast, "Diag", None)
    if Diag is None:  # pragma: no cover - ast.py always has it
        return (span, message, tuple(notes))
    return Diag(span=span, message=message, notes=tuple(notes))


# ---------------------------------------------------------------------------
# mangling
# ---------------------------------------------------------------------------

_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def comp(name: str) -> str:
    """One length-prefixed component."""
    text = str(name)
    if not _IDENT.match(text):
        # Zen identifiers are ASCII by the grammar; anything else is encoded
        # rather than emitted raw, and the caller raises a diagnostic.
        text = "x" + "".join("%02x" % b for b in text.encode("utf-8"))
    return "%d%s" % (len(text), text)


def clist(items) -> str:
    """A counted list of already-encoded strings."""
    items = tuple(items)
    return "%d_%s" % (len(items), "".join(items))


def path_code(parts) -> str:
    return clist([comp(p) for p in parts])


def sym_type(parts, args=()) -> str:
    return USR + tcode_named(parts, args)


def tcode_named(parts, args=()) -> str:
    out = "t" + path_code(parts)
    args = tuple(args)
    if args:
        out += "I" + clist([tcode(a) for a in args])
    return out


def sym_fn(parts, sig=(), targs=()) -> str:
    out = USR + "f" + path_code(parts)
    sig = tuple(sig)
    if sig:
        out += "O" + clist([tcode(t) for t in sig])
    targs = tuple(targs)
    if targs:
        out += "I" + clist([tcode(t) for t in targs])
    return out


def sym_variant(parts) -> str:
    return USR + "e" + path_code(parts)


def sym_member(name) -> str:
    return USR + "m" + comp(name)


def sym_local(name, n=1) -> str:
    return USR + "l" + comp(name) + ("" if n <= 1 else "_%d" % n)


def sym_value(parts) -> str:
    return USR + "v" + path_code(parts)


# ---------------------------------------------------------------------------
# the resolved type model
#
# Types are plain tuples: hashable, sortable, comparable, and printable without
# reference to any object identity.  That is what makes an instantiation name a
# function of the type rather than of the run.
#
#   ("prim", name)                i32, bool, str, ...
#   ("named", (path...), (args))  a declared struct / enum
#   ("ptr", T)
#   ("array", count, T)
#   ("fn", ret, (params...))
#   ("union", (members...))       members sorted by tcode
#   ("unit",)
#   ("unknown",)
# ---------------------------------------------------------------------------

PRIMS = {
    "i8": "int8_t",
    "i16": "int16_t",
    "i32": "int32_t",
    "i64": "int64_t",
    "u8": "uint8_t",
    "u16": "uint16_t",
    "u32": "uint32_t",
    "u64": "uint64_t",
    "usize": "size_t",
    "isize": "ptrdiff_t",
    "f32": "float",
    "f64": "double",
    "bool": "bool",
    "str": GEN + "str",
    "()": "void",
}

INT_LIMITS = {
    # name: (signed, bits, C min, C max)
    "i8": (True, 8, "INT8_MIN", "INT8_MAX"),
    "i16": (True, 16, "INT16_MIN", "INT16_MAX"),
    "i32": (True, 32, "INT32_MIN", "INT32_MAX"),
    "i64": (True, 64, "INT64_MIN", "INT64_MAX"),
    "isize": (True, 64, "PTRDIFF_MIN", "PTRDIFF_MAX"),
    "u8": (False, 8, "0", "UINT8_MAX"),
    "u16": (False, 16, "0", "UINT16_MAX"),
    "u32": (False, 32, "0", "UINT32_MAX"),
    "u64": (False, 64, "0", "UINT64_MAX"),
    "usize": (False, 64, "0", "SIZE_MAX"),
}

INT_VALUES = {
    "i8": (-128, 127, 8),
    "i16": (-32768, 32767, 16),
    "i32": (-2147483648, 2147483647, 32),
    "i64": (-9223372036854775808, 9223372036854775807, 64),
    "u8": (0, 255, 8),
    "u16": (0, 65535, 16),
    "u32": (0, 4294967295, 32),
    "u64": (0, 18446744073709551615, 64),
    "usize": (0, 18446744073709551615, 64),
    "isize": (-9223372036854775808, 9223372036854775807, 64),
}

UNIT = ("unit",)
UNKNOWN = ("unknown",)


def prim(name):
    return ("prim", name)


def tcode(t) -> str:
    """The name of a type.  A pure function of the type, and injective."""
    if t is None:
        return "q"
    k = t[0]
    if k == "prim":
        return "b" + comp(t[1])
    if k == "named":
        return tcode_named(t[1], t[2])
    if k == "ptr":
        return "p" + tcode(t[1])
    if k == "array":
        return "a%d_%s" % (t[1], tcode(t[2]))
    if k == "fn":
        return "f" + tcode(t[1]) + clist([tcode(p) for p in t[2]])
    if k == "union":
        return "u" + clist(sorted(tcode(m) for m in t[1]))
    if k == "unit":
        return "z"
    return "q"


def is_int(t):
    return t is not None and t[0] == "prim" and t[1] in INT_VALUES


def int_info(t):
    return INT_VALUES[t[1]]


def union_of(members):
    """Flatten and normalise a union; the member order is not observable."""
    flat = []
    for m in members:
        if m[0] == "union":
            flat.extend(m[1])
        else:
            flat.append(m)
    uniq = []
    for m in flat:
        if m not in uniq:
            uniq.append(m)
    if len(uniq) == 1:
        return uniq[0]
    return ("union", tuple(sorted(uniq, key=tcode)))


# ---------------------------------------------------------------------------
# source text, for the one thing the AST cannot answer
#
# A trap's position is the OPERATOR token (DESIGN.md, and every .stderr file in
# tests/corpus/traps/).  `Binary` and `Index` carry no operator span, so the
# operator is located by scanning the gap between the two operand spans,
# skipping whitespace and comments.  That is a function of the program text and
# therefore deterministic; when the text is unavailable the node's own span is
# used, which is the same file and line and at worst the wrong column.
# ---------------------------------------------------------------------------


class SourceMap:
    def __init__(self, root=None, sources=None):
        self.root = root
        self.given = dict(sources or {})
        self.cache = {}

    def _lines(self, relpath):
        if relpath in self.cache:
            return self.cache[relpath]
        text = self.given.get(relpath)
        if text is None and self.root is not None:
            try:
                with open(os.path.join(self.root, relpath), "rb") as fh:
                    text = fh.read().decode("utf-8", "replace")
            except OSError:
                text = None
        lines = text.splitlines(True) if text is not None else None
        self.cache[relpath] = lines
        return lines

    def gap(self, relpath, start, end):
        """The text between two (line, col) points, plus its start position."""
        lines = self._lines(relpath)
        if not lines:
            return None
        sl, sc = start
        el, ec = end
        if sl < 1 or el > len(lines) or (sl == el and ec < sc):
            return None
        out = []
        pos = []
        for ln in range(sl, min(el, len(lines)) + 1):
            raw = lines[ln - 1].encode("utf-8")
            lo = sc - 1 if ln == sl else 0
            hi = ec - 1 if ln == el else len(raw)
            lo = max(0, min(lo, len(raw)))
            hi = max(lo, min(hi, len(raw)))
            for i in range(lo, hi):
                out.append(raw[i : i + 1])
                pos.append((ln, i + 1))
        return b"".join(out), pos


def _skip_trivia(text, pos):
    """Index of the first byte of the first real token in `text`."""
    i = 0
    n = len(text)
    while i < n:
        c = text[i : i + 1]
        if c in b" \t\r\n":
            i += 1
            continue
        if text[i : i + 2] == b"//":
            j = text.find(b"\n", i)
            i = n if j < 0 else j + 1
            continue
        if text[i : i + 2] == b"/*":
            j = text.find(b"*/", i + 2)
            i = n if j < 0 else j + 2
            continue
        return i
    return None


class Positions:
    """`file:line:col` for a trap, with the operator token located."""

    def __init__(self, sources: SourceMap, root=None):
        self.sources = sources
        self.root = root

    def relfile(self, span):
        path = f(span, "file", "") or ""
        path = str(path).replace("\\", "/")
        if os.path.isabs(path) and self.root:
            try:
                path = os.path.relpath(path, self.root).replace("\\", "/")
            except ValueError:  # pragma: no cover - different drives
                path = os.path.basename(path)
        return path

    def of(self, node):
        span = f(node, "span")
        if span is None:
            return ("", 0, 0)
        start = f(span, "start", (0, 0)) or (0, 0)
        return (self.relfile(span), start[0], start[1])

    def operator(self, node, left, right):
        """The operator token between two operands, for a trap position."""
        explicit = f(node, "op_span")
        if explicit is not None:
            start = f(explicit, "start", (0, 0))
            return (self.relfile(explicit), start[0], start[1])
        lspan = f(left, "span")
        rspan = f(right, "span")
        span = f(node, "span")
        if lspan is not None and rspan is not None and span is not None:
            got = self.sources.gap(
                self.relfile(span),
                f(lspan, "end", (0, 0)),
                f(rspan, "start", (0, 0)),
            )
            if got:
                text, pos = got
                at = _skip_trivia(text, pos)
                if at is not None and at < len(pos):
                    line, col = pos[at]
                    return (self.relfile(span), line, col)
        return self.of(node)


# ---------------------------------------------------------------------------
# the program view
# ---------------------------------------------------------------------------


def modules_of(program):
    """Normalise whatever modules.py hands back into a sorted tuple."""
    mods = program
    for attr in ("modules", "graph", "roots"):
        got = getattr(program, attr, None)
        if got is not None:
            mods = got
            break
    if isinstance(mods, dict):
        mods = list(mods.values())
    try:
        mods = list(mods)
    except TypeError:
        mods = [mods]
    mods = [m for m in mods if kind(m) == "Module" or f(m, "decls") is not None]
    return tuple(sorted(mods, key=lambda m: (str(f(m, "name", "")), str(f(m, "path", "")))))


def module_parts(mod):
    """A module's mangling path: its dotted name, or its file path's stem."""
    name = f(mod, "name", None)
    if name:
        return tuple(str(name).split("."))
    path = str(f(mod, "path", "") or "")
    stem = os.path.splitext(os.path.basename(path))[0]
    return (stem or "module",)


class Decl:
    """One declaration, with everything gen_c needs to name and emit it."""

    __slots__ = ("mod", "parts", "node", "dkind", "name", "tparams")

    def __init__(self, mod, parts, node, dkind, name, tparams=()):
        self.mod = mod
        self.parts = tuple(parts)
        self.node = node
        self.dkind = dkind  # "type" | "fn" | "value"
        self.name = name
        self.tparams = tuple(tparams)


def _tparam_names(node):
    return tuple(str(f(tp, "name", "T")) for tp in (f(node, "tparams", ()) or ()))


def _is_fn_field(node):
    """A struct member whose value is a function: DESIGN.md's method form."""
    ty = f(node, "ty")
    if ty is not None and kind(ty) == "FnType":
        return True
    for attr in ("default", "value"):
        v = f(node, attr)
        if v is not None and kind(v) in ("Lambda", "Function"):
            return True
    return False


# ---------------------------------------------------------------------------
# the emitter
# ---------------------------------------------------------------------------


class Emitter:
    def __init__(self, program, sema=None, root=None, sources=None):
        self.program = program
        self.sema = sema
        self.root = root
        self.pos = Positions(SourceMap(root, sources), root)
        self.diags = []

        self.mods = modules_of(program)
        self.types = {}  # name -> ("struct"|"enum"|"array"|"union", payload)
        self.type_order = {}  # name -> deps (by-value)
        self.protos = {}  # cname -> prototype line
        self.bodies = {}  # cname -> body text
        self.helpers = set()  # generated arithmetic helpers actually used
        self.needs = set()  # generated runtime pieces actually used

        self.decls = {}  # (module parts, name) -> [Decl]
        self.by_name = {}  # name -> [Decl]  (module-agnostic fallback)
        self.worklist = []
        self.done = set()
        self.instances = 0
        self._collect()

    # -- collection --------------------------------------------------------

    def _add_decl(self, decl):
        self.decls.setdefault((decl.parts[:-1], decl.name), []).append(decl)
        self.by_name.setdefault(decl.name, []).append(decl)

    def _collect(self):
        for mod in self.mods:
            base = module_parts(mod)
            for node in f(mod, "decls", ()) or ():
                self._collect_decl(mod, base, node)

    def _collect_decl(self, mod, base, node):
        k = kind(node)
        name = f(node, "name", None)
        if k in ("Struct", "Enum", "Alias") and name:
            self._add_decl(Decl(mod, base + (str(name),), node, "type", str(name),
                                _tparam_names(node)))
            if k == "Struct":
                for member in f(node, "fields", ()) or ():
                    if _is_fn_field(member):
                        mname = str(f(member, "name", ""))
                        self._add_decl(
                            Decl(mod, base + (str(name), mname), member, "fn", mname,
                                 _tparam_names(member))
                        )
                for c in f(node, "consts", ()) or ():
                    cname = str(f(c, "name", ""))
                    self._add_decl(
                        Decl(mod, base + (str(name), cname), c, "value", cname)
                    )
        elif k == "Function" and name:
            self._add_decl(Decl(mod, base + (str(name),), node, "fn", str(name),
                                _tparam_names(node)))
        elif k == "Impl":
            target = str(f(node, "target", "") or "")
            trait = str(f(node, "trait", "") or "")
            for entry in f(node, "entries", ()) or ():
                ename = str(f(entry, "name", "") or "")
                if not ename:
                    continue
                self._add_decl(
                    Decl(mod, base + (target, trait, ename), entry, "fn", ename,
                         _tparam_names(entry))
                )
        elif k in ("Let", "Const") and isinstance(name, str):
            self._add_decl(Decl(mod, base + (str(name),), node, "value", str(name)))

    # -- lookup ------------------------------------------------------------

    def lookup(self, name, parts=(), dkind=None):
        """Declarations for a name, preferring the module in scope."""
        cands = []
        if parts:
            for n in range(len(parts), -1, -1):
                cands = self.decls.get((tuple(parts[:n]), name), [])
                if cands:
                    break
        if not cands:
            cands = self.by_name.get(name, [])
        if dkind:
            cands = [d for d in cands if d.dkind == dkind]
        return cands

    def type_decl(self, name, parts=()):
        got = self.lookup(name, parts, "type")
        return got[0] if got else None

    # -- types -------------------------------------------------------------

    def resolve_type(self, node, subst=None, parts=()):
        """An AST Type -> the tuple model."""
        subst = subst or {}
        if node is None:
            return UNKNOWN
        k = kind(node)
        if k == "Named":
            name = str(f(node, "name", ""))
            args = tuple(
                self.resolve_type(a, subst, parts) for a in (f(node, "args", ()) or ())
            )
            if name in subst and not args:
                return subst[name]
            if name in ("Ptr", "RawPtr"):
                return ("ptr", args[0] if args else prim("u8"))
            decl = self.type_decl(name, parts)
            if decl is None:
                if name in PRIMS:
                    return prim(name)
                if name == "@Self" and parts:
                    return ("named", tuple(parts), ())
                return UNKNOWN if name not in PRIMS else prim(name)
            if kind(decl.node) == "Alias":
                return self.resolve_type(f(decl.node, "target"), subst, decl.parts[:-1])
            return ("named", decl.parts, args)
        if k == "Union":
            return union_of(
                [self.resolve_type(m, subst, parts) for m in (f(node, "members", ()) or ())]
            )
        if k == "FnType":
            ret = self.resolve_type(f(node, "ret"), subst, parts)
            ps = tuple(
                self.resolve_type(f(p, "ty"), subst, parts)
                for p in (f(node, "params", ()) or ())
            )
            return ("fn", ret, ps)
        if k == "ArrayType":
            count = self.const_int(f(node, "count"), parts)
            elem = self.resolve_type(f(node, "elem"), subst, parts)
            return ("array", count if count is not None else 0, elem)
        if k == "Unit":
            return UNIT
        if k == "Infer":
            return UNKNOWN
        return UNKNOWN

    def const_int(self, expr, parts=()):
        """Comptime integer, for an array length.  Literals and Type.NAME."""
        if expr is None:
            return None
        k = kind(expr)
        if k == "Literal" and f(expr, "kind") == "int":
            return parse_int(f(expr, "text", "0"))
        if k == "Unary" and f(expr, "op") == "-":
            inner = self.const_int(f(expr, "operand"), parts)
            return None if inner is None else -inner
        if k == "Member":
            base = f(expr, "base")
            if kind(base) == "Path":
                got = self.builtin_type_const(str(f(base, "name", "")), str(f(expr, "name", "")))
                if got is not None:
                    return got[0]
        if k == "Path":
            got = self.lookup(str(f(expr, "name", "")), parts, "value")
            if got:
                return self.const_int(f(got[0].node, "value"), got[0].parts[:-1])
        return None

    def builtin_type_const(self, tyname, member):
        """i32.MAX / u8.MIN / i64.BITS, when std has not declared them."""
        if tyname not in INT_VALUES:
            return None
        lo, hi, bits = INT_VALUES[tyname]
        if member == "MIN":
            return (lo, prim(tyname))
        if member == "MAX":
            return (hi, prim(tyname))
        if member == "BITS":
            return (bits, prim("usize"))
        return None

    # -- C spelling of a type ---------------------------------------------

    def ctype(self, t):
        if t is None or t == UNKNOWN:
            return "int"  # a diagnostic has already been raised
        k = t[0]
        if k == "prim":
            name = t[1]
            if name == "str" and self.type_decl("str"):
                return self.request_type(("named", self.type_decl("str").parts, ()))
            return PRIMS.get(name, "int")
        if k == "unit":
            return "void"
        if k == "ptr":
            inner = self.ctype(t[1])
            return inner + " *"
        if k in ("named", "array", "union"):
            return self.request_type(t)
        if k == "fn":
            return GEN + "closure"
        return "int"

    def declarator(self, t, name):
        """A C declarator; pointers bind to the name, everything else does not."""
        spelling = self.ctype(t)
        if spelling.endswith("*"):
            return spelling + name
        return spelling + " " + name

    # -- type emission -----------------------------------------------------

    def request_type(self, t):
        """Register a type for emission and return its C name."""
        if t[0] == "named":
            cname = USR + tcode(t)
        else:
            cname = GEN + tcode(t)
        if cname in self.types:
            return cname
        self.types[cname] = None  # reserve, so recursion terminates
        if t[0] == "array":
            self.types[cname] = ("array", t)
            self.type_order[cname] = self._deps([t[2]])
        elif t[0] == "union":
            self.types[cname] = ("union", t)
            self.type_order[cname] = self._deps(list(t[1]))
        else:
            self._request_named(cname, t)
        return cname

    def _request_named(self, cname, t):
        parts, args = t[1], t[2]
        decl = None
        for d in self.by_name.get(parts[-1], []):
            if d.dkind == "type" and d.parts == parts:
                decl = d
                break
        if decl is None:
            self.types[cname] = ("opaque", t)
            self.type_order[cname] = ()
            return
        node = decl.node
        subst = dict(zip(decl.tparams, args))
        base = decl.parts[:-1]
        if len(args) != len(decl.tparams):
            self.error(node, "wrong number of type arguments for %s" % parts[-1])
        self.instances += 1
        if self.instances > MAX_INSTANCES:
            self.error(node, "generic instantiation did not terminate")
            self.types[cname] = ("opaque", t)
            self.type_order[cname] = ()
            return
        if kind(node) == "Struct":
            fields = []
            for member in f(node, "fields", ()) or ():
                if _is_fn_field(member):
                    continue  # a method is a function, not storage
                mname = str(f(member, "name", ""))
                mty = self.resolve_type(f(member, "ty"), subst, base)
                fields.append((mname, mty))
            self.types[cname] = ("struct", t, tuple(fields), decl)
            self.type_order[cname] = self._deps([ft for _, ft in fields])
            for _, ft in fields:
                self.ctype(ft)
        elif kind(node) == "Enum":
            variants = []
            for v in f(node, "variants", ()) or ():
                vname = str(f(v, "name", ""))
                payload = f(v, "payload")
                pty = self.resolve_type(payload, subst, base) if payload is not None else None
                variants.append((vname, pty))
            self.types[cname] = ("enum", t, tuple(variants), decl)
            self.type_order[cname] = self._deps([p for _, p in variants if p])
            for _, p in variants:
                if p:
                    self.ctype(p)
        else:  # Alias to a non-union type
            self.types[cname] = ("opaque", t)
            self.type_order[cname] = ()

    def _deps(self, tys):
        """By-value dependencies only; a pointer needs no complete type."""
        out = []
        for t in tys:
            if t is None:
                continue
            if t[0] in ("named", "array", "union"):
                out.append(self.request_type(t))
            elif t[0] == "prim" and t[1] == "str" and self.type_decl("str"):
                out.append(self.ctype(t))
        return tuple(sorted(set(out)))

    def variant_parts(self, t, vname):
        return tuple(t[1]) + (vname,)

    def enum_info(self, t):
        cname = self.request_type(t)
        entry = self.types.get(cname)
        if entry and entry[0] == "enum":
            return entry
        return None

    def struct_info(self, t):
        cname = self.request_type(t)
        entry = self.types.get(cname)
        if entry and entry[0] == "struct":
            return entry
        return None

    # -- diagnostics -------------------------------------------------------

    def error(self, node, message, notes=()):
        self.diags.append(_diag(f(node, "span"), message, notes))

    # ------------------------------------------------------------------ API

    def emit(self):
        """The whole program, as one C99 translation unit."""
        for decl in sorted(
            [d for ds in self.by_name.values() for d in ds if d.dkind == "fn"],
            key=lambda d: d.parts,
        ):
            if decl.tparams:
                continue  # a generic is emitted per instantiation
            self.request_fn(decl, ())
        self.drain()
        return self.assemble()

    def drain(self):
        guard = 0
        while self.worklist:
            guard += 1
            if guard > MAX_INSTANCES:
                break
            self.worklist.sort(key=lambda item: item[0])
            cname, decl, targs = self.worklist.pop(0)
            self.emit_fn(cname, decl, targs)

    def request_fn(self, decl, targs=()):
        node = decl.node
        fnode = self.fn_node(node)
        subst = dict(zip(decl.tparams, targs))
        sig = self.overload_sig(decl, subst)
        cname = sym_fn(decl.parts, sig, targs)
        if cname in self.done:
            return cname
        self.done.add(cname)
        if fnode is None or f(fnode, "body") is None:
            # required / hook forms have no body: no C function to emit
            return cname
        self.worklist.append((cname, decl, tuple(targs)))
        return cname

    def fn_node(self, node):
        """The Function/Lambda carrying params and a body for a declaration.

        A method is a struct member whose value is a function (DESIGN.md has
        one declaration form), so the member, its `default`/`value` and its
        `FnType` are all places the signature can be.
        """
        if kind(node) in ("Function", "Lambda"):
            return node
        for attr in ("default", "value"):
            v = f(node, attr)
            if v is not None and kind(v) in ("Function", "Lambda"):
                return v
        ty = f(node, "ty")
        if ty is not None and kind(ty) == "FnType":
            return node
        return None

    def params_of(self, fnode):
        if fnode is None:
            return ()
        got = f(fnode, "params")
        if got is None:
            ty = f(fnode, "ty")
            got = f(ty, "params") if ty is not None else None
        return tuple(got or ())

    def ret_of(self, fnode):
        if fnode is None:
            return None
        if f(fnode, "ret") is not None:
            return f(fnode, "ret")
        ty = f(fnode, "ty")
        return f(ty, "ret") if ty is not None else None

    def overload_sig(self, decl, subst):
        """Parameter types, but only for a name declared more than once.

        A pure function of the program: the count comes from the declaration
        table, never from the order calls were seen in.
        """
        siblings = [d for d in self.decls.get((decl.parts[:-1], decl.name), [])]
        if len(siblings) < 2:
            return ()
        fnode = self.fn_node(decl.node)
        if fnode is None:
            return ()
        return tuple(
            self.resolve_type(f(p, "ty"), subst, decl.parts[:-1])
            for p in self.params_of(fnode)
        )

    # ------------------------------------------------------- function bodies

    def emit_fn(self, cname, decl, targs):
        fnode = self.fn_node(decl.node)
        subst = dict(zip(decl.tparams, targs))
        base = decl.parts[:-1]
        params = list(self.params_of(fnode))
        ret = self.resolve_type(self.ret_of(fnode), subst, base)
        ctx = FnCtx(self, decl, subst, ret)

        decls = []
        for p in params:
            pname = str(f(p, "name", "_"))
            pty = self.resolve_type(f(p, "ty"), subst, base)
            if pty == UNKNOWN and self.sema is not None:
                pty = self.sema_type(p, base, subst) or pty
            cn = ctx.declare(pname, pty)
            decls.append(self.declarator(pty, cn))
        if not decls:
            decls = ["void"]
        head = "static %s(%s)" % (self.declarator(ret, cname), ", ".join(decls))
        self.protos[cname] = head + ";"

        body = f(fnode, "body")
        ctx.push()
        value = ctx.block_value(body, ret)
        if ret != UNIT and value is not None:
            ctx.line("return %s;" % value)
        elif ret != UNIT:
            ctx.line("return (%s){0};" % self.ctype(ret) if ret[0] != "prim" else "return 0;")
        ctx.pop()
        self.bodies[cname] = head + " {\n" + ctx.text() + "}\n"

    def sema_type(self, node, parts=(), subst=None):
        if self.sema is None:
            return None
        query = getattr(self.sema, "type_of", None)
        if query is None:
            return None
        try:
            got = query(node)
        except Exception:  # pragma: no cover - sema is another agent's file
            return None
        if got is None:
            return None
        return self.resolve_type(got, subst or {}, parts)

    # ------------------------------------------------------------- assembly

    def assemble(self):
        # `main` first: it can register one last type, and the type section
        # has to know about every type before it is written.
        entry = self.entry_point()
        types = self.emit_types()
        out = []
        out.append(BANNER)
        out.append(INCLUDES)
        out.append(self.prelude())
        out.append(types)
        out.append("/* ---- prototypes ---- */\n")
        for cname in sorted(self.protos):
            out.append(self.protos[cname] + "\n")
        out.append("\n/* ---- definitions ---- */\n\n")
        for cname in sorted(self.bodies):
            out.append(self.bodies[cname] + "\n")
        out.append(entry)
        return "".join(out)

    def prelude(self):
        parts = [PRELUDE_TYPES, PRELUDE_TRAP]
        if "print" in self.needs:
            parts.append(PRELUDE_PRINT)
        for name in sorted(self.helpers):
            parts.append(HELPERS[name])
        return "".join(parts)

    def emit_types(self):
        # Every tag is forward-declared before any definition: a by-value
        # field needs a complete type (so definitions are sorted by
        # dependency) and a cycle through Ptr cannot be sorted at all, so
        # both mechanisms are used rather than one.
        bodies = {}
        for _ in range(8):  # emitting a definition can register a new type
            todo = [n for n in sorted(self.types) if n not in bodies]
            if not todo:
                break
            for cname in self.topo(todo):
                bodies[cname] = self.emit_type(cname)
        out = ["/* ---- types ---- */\n"]
        for cname in sorted(self.types):
            out.append("typedef struct %s %s;\n" % (cname, cname))
        out.append("\n")
        for cname in self.topo(sorted(bodies)):
            out.append(bodies[cname])
        return "".join(out)

    def topo(self, names):
        """Definition order: dependencies first, ties broken by name.

        Every tag is forward-declared above, so only by-value containment
        constrains this; a genuine by-value cycle is a sema error and is
        broken here by name so that emission still terminates.
        """
        pending = {n: set(self.type_order.get(n, ())) & set(names) for n in names}
        emitted = []
        done = set()
        while pending:
            ready = sorted(n for n, deps in pending.items() if not (deps - done))
            if not ready:
                ready = [sorted(pending)[0]]
                entry = self.types.get(ready[0])
                if entry:
                    self.diags.append(
                        _diag(None, "type %s is part of a by-value cycle" % ready[0])
                    )
            for n in ready:
                emitted.append(n)
                done.add(n)
                pending.pop(n, None)
        return emitted

    def emit_type(self, cname):
        entry = self.types.get(cname)
        if entry is None or entry[0] == "opaque":
            return "struct %s { char %spad; };\n\n" % (cname, GEN)
        if entry[0] == "struct":
            _, t, fields, _decl = entry
            lines = ["struct %s {\n" % cname]
            if not fields:
                # C11 6.7.2.1p1 requires a member; one byte, in exactly one
                # place, so a bare Empty and an Empty field agree.
                lines.append("    char %spad;\n" % GEN)
            for fname, fty in fields:
                lines.append("    %s;\n" % self.declarator(fty, sym_member(fname)))
            lines.append("};\n\n")
            return "".join(lines)
        if entry[0] == "enum":
            _, t, variants, _decl = entry
            lines = []
            lines.append("enum {\n")
            for i, (vname, _p) in enumerate(variants):
                lines.append(
                    "    %s = %d,\n" % (sym_variant(self.variant_parts(t, vname)), i)
                )
            lines.append("};\n")
            lines.append("struct %s {\n    int32_t %stag;\n" % (cname, GEN))
            payloads = [(v, p) for v, p in variants if p is not None]
            if payloads:
                lines.append("    union {\n")
                for vname, pty in payloads:
                    lines.append("        %s;\n" % self.declarator(pty, sym_member(vname)))
                lines.append("    } %sdata;\n" % GEN)
            lines.append("};\n\n")
            return "".join(lines)
        if entry[0] == "array":
            _, t = entry
            return "struct %s {\n    %s;\n};\n\n" % (
                cname,
                self.declarator(t[2], "%selems[%d]" % (GEN, max(t[1], 1))),
            )
        if entry[0] == "union":
            _, t = entry
            members = tuple(sorted(t[1], key=tcode))
            lines = ["enum {\n"]
            for i, m in enumerate(members):
                lines.append("    %stag%s = %d,\n" % (GEN, tcode(m), i))
            lines.append("};\n")
            lines.append("struct %s {\n    int32_t %stag;\n    union {\n" % (cname, GEN))
            for m in members:
                lines.append("        %s;\n" % self.declarator(m, GEN + "m" + tcode(m)))
            lines.append("    } %sdata;\n};\n\n" % GEN)
            return "".join(lines)
        return ""

    def entry_point(self):
        """`main`, the one name the C standard fixes for us."""
        cands = [d for d in self.by_name.get("main", []) if d.dkind == "fn"]
        if not cands:
            return ""
        decl = sorted(cands, key=lambda d: d.parts)[0]
        fnode = self.fn_node(decl.node)
        if fnode is None:
            return ""
        cname = sym_fn(decl.parts, self.overload_sig(decl, {}), ())
        ret = self.resolve_type(self.ret_of(fnode), {}, decl.parts[:-1])
        nparams = len(self.params_of(fnode))
        args = []
        for p in self.params_of(fnode):
            pty = self.resolve_type(f(p, "ty"), {}, decl.parts[:-1])
            args.append("(%s){0}" % self.ctype(pty) if pty[0] != "prim" else "0")
        body = ["int main(int argc, char **argv) {\n"]
        body.append("    %sargc = argc;\n    %sargv = argv;\n" % (GEN, GEN))
        call = "%s(%s)" % (cname, ", ".join(args) if nparams else "")
        info = self.enum_info(ret) if ret[0] == "named" else None
        if info:
            names = [v for v, _ in info[2]]
            ok = "Ok" if "Ok" in names else names[0]
            body.append("    %s r = %s;\n" % (self.ctype(ret), call))
            payload = dict(info[2]).get(ok)
            if payload is not None and is_int(payload):
                body.append(
                    "    if (r.%stag == %s) return (int)r.%sdata.%s;\n"
                    % (GEN, sym_variant(self.variant_parts(ret, ok)), GEN, sym_member(ok))
                )
            else:
                body.append(
                    "    if (r.%stag == %s) return 0;\n"
                    % (GEN, sym_variant(self.variant_parts(ret, ok)))
                )
            body.append("    return 1;\n")
        elif is_int(ret):
            body.append("    return (int)%s;\n" % call)
        else:
            body.append("    %s;\n    return 0;\n" % call)
        body.append("}\n")
        return "".join(body)


# ---------------------------------------------------------------------------
# per-function lowering
#
# Everything is lowered to statements plus a result temporary.  TESTING.md's
# nesting corpus is the reason: gen_c may not assume its output nesting is
# bounded by its input nesting, so a match, a block-as-value and any operation
# that traps all spill, and an expression deeper than MAX_EXPR_DEPTH spills too.
# ---------------------------------------------------------------------------


class FnCtx:
    def __init__(self, emitter, decl, subst, ret):
        self.e = emitter
        self.decl = decl
        self.parts = decl.parts[:-1]
        self.subst = subst
        self.ret = ret
        self.lines = []
        self.indent = 1
        self.scopes = [{}]
        self.counts = {}
        self.tmp = 0
        self.depth = 0

    # -- output ------------------------------------------------------------

    def line(self, text):
        self.lines.append("    " * self.indent + text + "\n")

    def open(self, text="{"):
        self.line(text)
        self.indent += 1

    def close(self, text="}"):
        self.indent -= 1
        self.line(text)

    def text(self):
        return "".join(self.lines)

    def new_tmp(self, ty):
        self.tmp += 1
        name = "%st%d" % (GEN, self.tmp)
        if ty is not None and ty != UNIT:
            self.line(self.e.declarator(ty, name) + ";")
        return name

    # -- scopes ------------------------------------------------------------

    def push(self):
        self.scopes.append({})

    def pop(self):
        self.scopes.pop()

    def declare(self, name, ty):
        n = self.counts.get(name, 0) + 1
        self.counts[name] = n
        cname = sym_local(name, n)
        self.scopes[-1][name] = (cname, ty)
        return cname

    def find(self, name):
        for scope in reversed(self.scopes):
            if name in scope:
                return scope[name]
        return None

    # -- statements --------------------------------------------------------

    def block_value(self, block, want=None):
        """Emit a Block's statements; return its value expression, if any."""
        if block is None:
            return None
        if kind(block) != "Block":
            return self.expr(block)[0]
        for stmt in f(block, "stmts", ()) or ():
            self.stmt(stmt)
        value = f(block, "value")
        if value is None:
            return None
        code, _ty = self.expr(value)
        return code

    def stmt(self, node):
        k = kind(node)
        if k == "Let":
            self.let(node)
        elif k == "ExprStmt":
            self.expr_stmt(f(node, "expr"))
        elif k == "Block":
            self.push()
            self.open()
            self.block_value(node)
            self.close()
            self.pop()
        elif k in ("Struct", "Enum", "Alias", "Function", "Impl"):
            pass  # a nested declaration; collected, not emitted here
        else:
            self.expr_stmt(node)

    def let(self, node):
        name = f(node, "name")
        value = f(node, "value")
        declared = f(node, "ty")
        if not isinstance(name, str):
            # `self.len = ..` / `buf[i] = ..`: the target is an lvalue node
            target, _ty = self.expr(name)
            code, _vt = self.expr(value)
            self.line("%s = %s;" % (target, code))
            return
        existing = self.find(name)
        want = (
            self.e.resolve_type(declared, self.subst, self.parts)
            if declared is not None
            else (existing[1] if existing else None)
        )
        code, ty = self.expr(value, want)
        if existing is not None and declared is None and not f(node, "mutable", False):
            # a second binding of a name already in scope is an assignment:
            # Zen writes a declaration and a store the same way
            self.line("%s = %s;" % (existing[0], code))
            return
        ty = want or ty or UNKNOWN
        if ty == UNKNOWN:
            self.e.error(node, "cannot infer a type for `%s`" % name)
        cname = self.declare(name, ty)
        self.line("%s = %s;" % (self.e.declarator(ty, cname), code))

    def expr_stmt(self, node):
        if node is None:
            return
        k = kind(node)
        if k == "Binary" and f(node, "op") == "=":
            target, _ = self.expr(f(node, "lhs"))
            code, _ = self.expr(f(node, "rhs"))
            self.line("%s = %s;" % (target, code))
            return
        code, ty = self.expr(node)
        if code and code not in ("", "0"):
            self.line("(void)(%s);" % code)

    # -- expressions -------------------------------------------------------

    def expr(self, node, want=None):
        """-> (C expression text, resolved type).  May emit statements."""
        if node is None:
            return ("0", UNKNOWN)
        self.depth += 1
        try:
            if self.depth > MAX_EXPR_DEPTH:
                code, ty = self._expr(node, want)
                if ty not in (UNIT, UNKNOWN) and not code.isidentifier():
                    tmp = self.new_tmp(ty)
                    self.line("%s = %s;" % (tmp, code))
                    return (tmp, ty)
                return (code, ty)
            return self._expr(node, want)
        finally:
            self.depth -= 1

    def _expr(self, node, want=None):
        k = kind(node)
        method = getattr(self, "ex_" + k, None)
        if method is None:
            self.e.error(node, "gen_c cannot lower a %s expression" % k)
            return ("0", UNKNOWN)
        return method(node, want)

    # literals ------------------------------------------------------------

    def ex_Literal(self, node, want=None):
        lk = f(node, "kind")
        text = str(f(node, "text", ""))
        if lk == "int":
            value = parse_int(text)
            ty = want if is_int(want) else prim("i32")
            return (int_literal(value, ty), ty)
        if lk == "float":
            ty = want if want and want[0] == "prim" and want[1] in ("f32", "f64") else prim("f64")
            return (float_literal(text), ty)
        if lk == "bool":
            return ("true" if text.strip() in ("true", "1") else "false", prim("bool"))
        if lk == "char":
            return (str(decode_char(text)), prim("u8"))
        if lk == "str":
            return (self.str_literal(decode_str(text)), self.str_type())
        self.e.error(node, "unknown literal kind %r" % lk)
        return ("0", UNKNOWN)

    def str_type(self):
        decl = self.e.type_decl("str")
        return ("named", decl.parts, ()) if decl else prim("str")

    def str_names(self):
        decl = self.e.type_decl("str")
        if decl is None:
            return ("data", "len", False)
        return ("data", "len", True)

    def str_literal(self, raw: bytes):
        ty = self.str_type()
        cname = self.e.ctype(ty)
        data, length, user = self.str_names()
        dname = sym_member(data) if user else "data"
        lname = sym_member(length) if user else "len"
        return "((%s){ .%s = (const unsigned char *)%s, .%s = %d })" % (
            cname,
            dname,
            c_string(raw),
            lname,
            len(raw),
        )

    def ex_Path(self, node, want=None):
        name = str(f(node, "name", ""))
        local = self.find(name)
        if local:
            return local
        vals = self.e.lookup(name, self.parts, "value")
        if vals:
            d = vals[0]
            code, ty = self.expr(f(d.node, "value"), want)
            return (code, ty)
        fns = self.e.lookup(name, self.parts, "fn")
        if fns:
            d = fns[0]
            cn = self.e.request_fn(d, ())
            fnode = self.e.fn_node(d.node)
            ret = self.e.resolve_type(self.e.ret_of(fnode), {}, d.parts[:-1])
            return (cn, ("fn", ret, ()))
        tys = self.e.lookup(name, self.parts, "type")
        if tys:
            return (name, ("named", tys[0].parts, ()))
        self.e.error(node, "unresolved name `%s`" % name)
        return ("0", UNKNOWN)

    def ex_Member(self, node, want=None):
        base = f(node, "base")
        name = str(f(node, "name", ""))
        # Type.NAME -- an enum variant, a type constant, or a module member
        if kind(base) == "Path":
            bname = str(f(base, "name", ""))
            if self.find(bname) is None:
                got = self.e.builtin_type_const(bname, name)
                if got is not None and not self.e.lookup(bname, self.parts, "type"):
                    value, ty = got
                    return (int_literal(value, ty), ty)
                tdecl = self.e.type_decl(bname, self.parts)
                if tdecl is not None:
                    lit = self.type_member(tdecl, name, node)
                    if lit is not None:
                        return lit
                mod = self.module_named(bname)
                if mod is not None:
                    return self.module_member(mod, name, node)
        code, ty = self.expr(base)
        if ty is not None and ty[0] == "named":
            info = self.e.struct_info(ty)
            if info:
                for fname, fty in info[2]:
                    if fname == name:
                        return ("%s.%s" % (paren(code), sym_member(name)), fty)
                method = self.method_of(ty, name)
                if method is not None:
                    return (method, UNKNOWN)
        if ty is not None and ty[0] == "prim" and ty[1] == "str" and name == "len":
            return ("%s.len" % paren(code), prim("usize"))
        self.e.error(node, "no member `%s` on this value" % name)
        return ("0", UNKNOWN)

    def type_member(self, tdecl, name, node):
        node_t = tdecl.node
        if kind(node_t) == "Enum":
            for v in f(node_t, "variants", ()) or ():
                if str(f(v, "name", "")) == name and f(v, "payload") is None:
                    ty = ("named", tdecl.parts, ())
                    return (self.make_variant(ty, name, None), ty)
                if str(f(v, "name", "")) == name:
                    return None  # a payload variant: handled at the Call
        for c in f(node_t, "consts", ()) or ():
            if str(f(c, "name", "")) == name:
                return self.expr(f(c, "value"))
        return None

    def module_named(self, name):
        for mod in self.e.mods:
            if module_parts(mod)[-1] == name or str(f(mod, "name", "")) == name:
                return mod
        return None

    def module_member(self, mod, name, node):
        base = module_parts(mod)
        for dkind in ("fn", "value", "type"):
            got = self.e.decls.get((base, name), [])
            got = [d for d in got if d.dkind == dkind]
            if got:
                if dkind == "fn":
                    cn = self.e.request_fn(got[0], ())
                    return (cn, UNKNOWN)
                if dkind == "value":
                    return self.expr(f(got[0].node, "value"))
                return (name, ("named", got[0].parts, ()))
        self.e.error(node, "module has no member `%s`" % name)
        return ("0", UNKNOWN)

    def method_of(self, ty, name):
        parts = tuple(ty[1]) + (name,)
        for d in self.e.by_name.get(name, []):
            if d.dkind == "fn" and d.parts == parts:
                return self.e.request_fn(d, ())
        return None

    def ex_Index(self, node, want=None):
        base = f(node, "base")
        index = f(node, "index")
        bcode, bty = self.expr(base)
        icode, ity = self.expr(index, prim("usize"))
        if bty is not None and bty[0] == "array":
            file, line, col = self.e.pos.operator(node, base, index)
            helper = "idx_u" if not (is_int(ity) and int_info(ity)[0] < 0) else "idx_s"
            self.e.helpers.add(helper)
            checked = "%s%s(%s, %d, %s, %d, %d)" % (
                GEN,
                helper,
                icode,
                bty[1],
                c_string(file.encode("utf-8")),
                line,
                col,
            )
            return ("%s.%selems[%s]" % (paren(bcode), GEN, checked), bty[2])
        if bty is not None and bty[0] == "ptr":
            # a raw pointer carries no length: DESIGN.md bounds-checks fixed
            # arrays, and Vec.get returns a Res instead
            return ("%s[%s]" % (paren(bcode), icode), bty[1])
        self.e.error(node, "value is not indexable")
        return ("0", UNKNOWN)

    def ex_Unary(self, node, want=None):
        op = f(node, "op")
        operand = f(node, "operand")
        code, ty = self.expr(operand, want)
        if op == "-":
            if kind(operand) == "Literal" and f(operand, "kind") == "int":
                value = -parse_int(str(f(operand, "text", "0")))
                t = want if is_int(want) else prim("i32")
                return (int_literal(value, t), t)
            if is_int(ty):
                file, line, col = self.e.pos.of(node)
                helper = "sub_" + ty[1]
                self.e.helpers.add(helper)
                return (
                    "%s%s(0, %s, %s, %d, %d)"
                    % (GEN, helper, code, c_string(file.encode("utf-8")), line, col),
                    ty,
                )
            return ("(-%s)" % paren(code), ty)
        if op == "!":
            return ("(!%s)" % paren(code), prim("bool"))
        if op == "&":
            return ("(&%s)" % paren(code), ("ptr", ty or UNKNOWN))
        self.e.error(node, "unknown unary operator %r" % op)
        return ("0", UNKNOWN)

    def ex_Consume(self, node, want=None):
        # `consume` is a move; ownership is stage 3's checker, and the value
        # itself is unchanged, so this is the operand.
        return self.expr(f(node, "operand"), want)

    def ex_Binary(self, node, want=None):
        op = str(f(node, "op", ""))
        lhs, rhs = f(node, "lhs"), f(node, "rhs")
        if op == "=":
            target, tty = self.expr(lhs)
            code, _ = self.expr(rhs, tty)
            self.line("%s = %s;" % (target, code))
            return (target, tty)
        if op in ("&&", "||"):
            # short circuit, with the right-hand side's statements guarded
            lcode, _ = self.expr(lhs, prim("bool"))
            tmp = self.new_tmp(prim("bool"))
            self.line("%s = %s;" % (tmp, lcode))
            self.open("if (%s%s) {" % ("" if op == "&&" else "!", paren(tmp)))
            rcode, _ = self.expr(rhs, prim("bool"))
            self.line("%s = %s;" % (tmp, rcode))
            self.close()
            return (tmp, prim("bool"))
        lcode, lty = self.expr(lhs, want if op in ARITH or op in WRAPPING else None)
        rcode, rty = self.expr(rhs, lty if is_int(lty) else None)
        ty = lty if lty not in (None, UNKNOWN) else rty
        if op in COMPARE:
            return ("(%s %s %s)" % (paren(lcode), op, paren(rcode)), prim("bool"))
        if op in WRAPPING:
            base = {"+%": "wadd", "-%": "wsub", "*%": "wmul"}[op]
            if is_int(ty):
                name = "%s_%s" % (base, ty[1])
                self.e.helpers.add(name)
                return ("%s%s(%s, %s)" % (GEN, name, lcode, rcode), ty)
            return ("(%s %s %s)" % (paren(lcode), op[0], paren(rcode)), ty)
        if op in ARITH:
            if is_int(ty):
                base = {"+": "add", "-": "sub", "*": "mul", "/": "div", "%": "mod"}[op]
                name = "%s_%s" % (base, ty[1])
                self.e.helpers.add(name)
                file, line, col = self.e.pos.operator(node, lhs, rhs)
                out = "%s%s(%s, %s, %s, %d, %d)" % (
                    GEN,
                    name,
                    lcode,
                    rcode,
                    c_string(file.encode("utf-8")),
                    line,
                    col,
                )
                tmp = self.new_tmp(ty)
                self.line("%s = %s;" % (tmp, out))
                return (tmp, ty)
            return ("(%s %s %s)" % (paren(lcode), op, paren(rcode)), ty)
        self.e.error(node, "unknown binary operator %r" % op)
        return ("0", UNKNOWN)

    # calls ---------------------------------------------------------------

    def ex_Call(self, node, want=None):
        callee = f(node, "callee")
        args = list(f(node, "args", ()) or ())
        targs = list(f(node, "targs", ()) or ())
        ck = kind(callee)

        if ck == "Path":
            name = str(f(callee, "name", ""))
            if name == "println" or name == "print":
                return self.lower_print(node, args, newline=(name == "println"))
            built = self.try_construct(name, node, args, targs, want)
            if built is not None:
                return built
            got = self.call_named(name, node, args, targs, want)
            if got is not None:
                return got
        if ck == "Member":
            got = self.call_member(callee, node, args, targs, want)
            if got is not None:
                return got
        # a computed callee: a function value
        code, ty = self.expr(callee)
        argv = [self.expr(f(a, "value") if kind(a) == "Arg" else a)[0] for a in args]
        ret = ty[1] if ty and ty[0] == "fn" else UNKNOWN
        return ("%s(%s)" % (code, ", ".join(argv)), ret)

    def arg_nodes(self, args):
        return [f(a, "value") if kind(a) == "Arg" else a for a in args]

    def try_construct(self, name, node, args, targs, want):
        """`Point(x: 1, y: 2)`, `Shape.Circle(c)`, `[i32, 4](..)`."""
        tdecl = self.e.type_decl(name, self.parts)
        if tdecl is None:
            return None
        if kind(tdecl.node) == "Enum":
            return None  # a bare enum name is not a constructor
        targ_tys = tuple(self.e.resolve_type(t, self.subst, self.parts) for t in targs)
        if not targ_tys and tdecl.tparams:
            targ_tys = self.infer_targs(tdecl, args)
        ty = ("named", tdecl.parts, targ_tys)
        info = self.e.struct_info(ty)
        if info is None:
            return None
        fields = dict(info[2])
        order = [fname for fname, _ in info[2]]
        values = {}
        positional = []
        for a in args:
            aname = f(a, "name") if kind(a) == "Arg" else None
            value = f(a, "value") if kind(a) == "Arg" else a
            if aname:
                values[str(aname)] = value
            else:
                positional.append(value)
        for i, value in enumerate(positional):
            if i < len(order):
                values.setdefault(order[i], value)
        inits = []
        for fname in order:
            if fname in values:
                code, _ = self.expr(values[fname], fields.get(fname))
                inits.append(".%s = %s" % (sym_member(fname), code))
        cname = self.e.ctype(ty)
        if not inits:
            return ("((%s){0})" % cname, ty)
        return ("((%s){ %s })" % (cname, ", ".join(inits)), ty)

    def infer_targs(self, tdecl, args):
        """Type arguments from the argument types, positionally by field."""
        info_fields = []
        node = tdecl.node
        for member in f(node, "fields", ()) or ():
            if not _is_fn_field(member):
                info_fields.append((str(f(member, "name", "")), f(member, "ty")))
        found = {}
        argmap = {}
        pos = []
        for a in args:
            aname = f(a, "name") if kind(a) == "Arg" else None
            value = f(a, "value") if kind(a) == "Arg" else a
            if aname:
                argmap[str(aname)] = value
            else:
                pos.append(value)
        for i, (fname, fty) in enumerate(info_fields):
            value = argmap.get(fname)
            if value is None and i < len(pos):
                value = pos[i]
            if value is None or fty is None:
                continue
            _code, aty = self.peek(value)
            self.unify(fty, aty, found)
        return tuple(found.get(tp, UNKNOWN) for tp in tdecl.tparams)

    def peek(self, node):
        """Type of an expression without emitting anything."""
        saved = (list(self.lines), self.tmp, self.indent)
        try:
            code, ty = self.expr(node)
        finally:
            self.lines, self.tmp, self.indent = saved[0], saved[1], saved[2]
        return (code, ty)

    def unify(self, tynode, actual, found):
        if tynode is None or actual is None:
            return
        if kind(tynode) == "Named":
            name = str(f(tynode, "name", ""))
            args = f(tynode, "args", ()) or ()
            if not args and name not in PRIMS and self.is_tparam(name):
                found.setdefault(name, actual)
                return
            if actual[0] == "named" and args:
                for sub, act in zip(args, actual[2]):
                    self.unify(sub, act, found)
            if name in ("Ptr", "RawPtr") and actual[0] == "ptr" and args:
                self.unify(args[0], actual[1], found)

    def is_tparam(self, name):
        return name in self.subst or name in getattr(self, "_tparams", ()) or (
            len(name) <= 2 and name[0].isupper()
        )

    def call_named(self, name, node, args, targs, want):
        cands = self.e.lookup(name, self.parts, "fn")
        if not cands:
            return None
        argnodes = self.arg_nodes(args)
        decl = self.pick_overload(cands, argnodes)
        return self.emit_call(decl, node, argnodes, targs, want)

    def call_member(self, callee, node, args, targs, want):
        base = f(callee, "base")
        name = str(f(callee, "name", ""))
        if name == "match":
            return None  # Match is its own node
        if kind(base) == "Path" and self.find(str(f(base, "name", ""))) is None:
            bname = str(f(base, "name", ""))
            tdecl = self.e.type_decl(bname, self.parts)
            if tdecl is not None and kind(tdecl.node) == "Enum":
                return self.construct_variant(tdecl, name, node, args, targs, want)
            mod = self.module_named(bname)
            if mod is not None:
                base_parts = module_parts(mod)
                cands = [
                    d for d in self.e.decls.get((base_parts, name), []) if d.dkind == "fn"
                ]
                if cands:
                    argnodes = self.arg_nodes(args)
                    decl = self.pick_overload(cands, argnodes)
                    return self.emit_call(decl, node, argnodes, targs, want)
        rcode, rty = self.expr(base)
        argnodes = self.arg_nodes(args)
        if rty is not None and rty[0] == "ptr":
            got = self.ptr_method(rcode, rty, name, argnodes, node)
            if got is not None:
                return got
        if rty is not None and rty[0] == "named":
            parts = tuple(rty[1]) + (name,)
            cands = [d for d in self.e.by_name.get(name, []) if d.dkind == "fn" and d.parts == parts]
            if not cands:
                cands = [
                    d
                    for d in self.e.by_name.get(name, [])
                    if d.dkind == "fn" and len(d.parts) >= 2 and d.parts[-2] == rty[1][-1]
                ]
            if cands:
                decl = self.pick_overload(cands, argnodes)
                return self.emit_call(decl, node, argnodes, targs, want, receiver=(rcode, rty))
        # a ufcs free function: the receiver is the first parameter
        cands = self.e.lookup(name, self.parts, "fn")
        if cands:
            decl = self.pick_overload(cands, argnodes)
            return self.emit_call(decl, node, argnodes, targs, want, receiver=(rcode, rty))
        self.e.error(node, "no method `%s` on this value" % name)
        return ("0", UNKNOWN)

    def ptr_method(self, rcode, rty, name, argnodes, node):
        """Ptr<T>.read(i) / .write(i, v) -- the raw floor, when std is absent."""
        if name == "read" and len(argnodes) == 1:
            icode, _ = self.expr(argnodes[0], prim("usize"))
            return ("%s[%s]" % (paren(rcode), icode), rty[1])
        if name == "write" and len(argnodes) == 2:
            icode, _ = self.expr(argnodes[0], prim("usize"))
            vcode, _ = self.expr(argnodes[1], rty[1])
            self.line("%s[%s] = %s;" % (paren(rcode), icode, vcode))
            return ("0", UNIT)
        return None

    def pick_overload(self, cands, argnodes):
        """Resolution on arity, then on declared parameter types."""
        cands = sorted(cands, key=lambda d: d.parts)
        if len(cands) == 1:
            return cands[0]
        want = len(argnodes)
        by_arity = []
        for d in cands:
            fnode = self.e.fn_node(d.node)
            n = len(self.e.params_of(fnode)) if fnode else -1
            if n == want or n == want + 1:
                by_arity.append(d)
        return (by_arity or cands)[0]

    def construct_variant(self, tdecl, vname, node, args, targs, want):
        targ_tys = tuple(self.e.resolve_type(t, self.subst, self.parts) for t in targs)
        if not targ_tys and tdecl.tparams and want is not None and want[0] == "named":
            if want[1] == tdecl.parts:
                targ_tys = want[2]
        if not targ_tys and tdecl.tparams:
            argnodes = self.arg_nodes(args)
            if argnodes:
                _c, aty = self.peek(argnodes[0])
                targ_tys = tuple(aty for _ in tdecl.tparams)
        ty = ("named", tdecl.parts, targ_tys)
        argnodes = self.arg_nodes(args)
        payload = None
        if argnodes:
            info = self.e.enum_info(ty)
            pty = dict(info[2]).get(vname) if info else None
            payload = self.expr(argnodes[0], pty)[0]
        return (self.make_variant(ty, vname, payload), ty)

    def make_variant(self, ty, vname, payload):
        cname = self.e.ctype(ty)
        tag = sym_variant(self.e.variant_parts(ty, vname))
        if payload is None:
            return "((%s){ .%stag = %s })" % (cname, GEN, tag)
        return "((%s){ .%stag = %s, .%sdata = { .%s = %s } })" % (
            cname,
            GEN,
            tag,
            GEN,
            sym_member(vname),
            payload,
        )

    def emit_call(self, decl, node, argnodes, targs, want, receiver=None):
        fnode = self.e.fn_node(decl.node)
        if fnode is None:
            self.e.error(node, "`%s` is not callable" % decl.name)
            return ("0", UNKNOWN)
        params = list(self.e.params_of(fnode))
        targ_tys = tuple(self.e.resolve_type(t, self.subst, self.parts) for t in targs)
        values = list(argnodes)
        codes = []
        if receiver is not None:
            codes.append(receiver[0])
        if decl.tparams and not targ_tys:
            targ_tys = self.infer_fn_targs(decl, fnode, values, receiver)
        subst = dict(zip(decl.tparams, targ_tys))
        for i, value in enumerate(values):
            idx = i + (1 if receiver is not None else 0)
            pty = (
                self.e.resolve_type(f(params[idx], "ty"), subst, decl.parts[:-1])
                if idx < len(params)
                else None
            )
            codes.append(self.expr(value, pty)[0])
        cname = self.e.request_fn(decl, targ_tys)
        ret = self.e.resolve_type(self.e.ret_of(fnode), subst, decl.parts[:-1])
        return ("%s(%s)" % (cname, ", ".join(codes)), ret)

    def infer_fn_targs(self, decl, fnode, values, receiver):
        params = list(self.e.params_of(fnode))
        found = {}
        offset = 1 if receiver is not None else 0
        if receiver is not None and params:
            self.unify(f(params[0], "ty"), receiver[1], found)
        for i, value in enumerate(values):
            idx = i + offset
            if idx >= len(params):
                break
            _c, aty = self.peek(value)
            self.unify(f(params[idx], "ty"), aty, found)
        return tuple(found.get(tp, UNKNOWN) for tp in decl.tparams)

    # print ---------------------------------------------------------------

    def lower_print(self, node, args, newline=True):
        """`println("a {} b", x)` -> typed writes, one call per piece.

        std owns `println` once it exists (DESIGN.md routes it through the
        `Env` in scope); until then this is the builtin that makes the corpus
        runnable.  `{}` on an integer prints decimal with no separators and
        `println` appends exactly one newline, per TESTING.md.
        """
        self.e.needs.add("print")
        argnodes = self.arg_nodes(args)
        if not argnodes:
            self.line("%sprint_nl();" % GEN)
            return ("0", UNIT)
        fmt_node = argnodes[0]
        rest = argnodes[1:]
        if kind(fmt_node) == "Literal" and f(fmt_node, "kind") == "str":
            raw = decode_str(str(f(fmt_node, "text", "")))
            pieces = raw.split(b"{}")
            for i, piece in enumerate(pieces):
                if piece:
                    self.line(
                        "%sprint_bytes(%s, %d);" % (GEN, c_string(piece), len(piece))
                    )
                if i < len(pieces) - 1:
                    if i < len(rest):
                        self.print_value(rest[i])
                    else:
                        self.line("%sprint_bytes(\"{}\", 2);" % GEN)
            for extra in rest[len(pieces) - 1 :]:
                self.print_value(extra)
        else:
            self.print_value(fmt_node)
            for extra in rest:
                self.print_value(extra)
        if newline:
            self.line("%sprint_nl();" % GEN)
        return ("0", UNIT)

    def print_value(self, node):
        code, ty = self.expr(node)
        if ty is not None and ty[0] == "prim":
            name = ty[1]
            if name == "bool":
                self.line("%sprint_bool(%s);" % (GEN, code))
                return
            if name in ("f32", "f64"):
                self.line("%sprint_f64((double)%s);" % (GEN, paren(code)))
                return
            if name in INT_VALUES:
                signed = INT_VALUES[name][0] < 0
                if signed:
                    self.line("%sprint_i64((int64_t)%s);" % (GEN, paren(code)))
                else:
                    self.line("%sprint_u64((uint64_t)%s);" % (GEN, paren(code)))
                return
            if name == "str":
                self.line("%sprint_bytes((const char *)%s.data, %s.len);" % (GEN, paren(code), paren(code)))
                return
        if ty is not None and ty[0] == "named":
            info = self.e.struct_info(ty)
            names = [n for n, _ in info[2]] if info else []
            if info and "data" in names and "len" in names:
                tmp = self.new_tmp(ty)
                self.line("%s = %s;" % (tmp, code))
                self.line(
                    "%sprint_bytes((const char *)%s.%s, (size_t)%s.%s);"
                    % (GEN, tmp, sym_member("data"), tmp, sym_member("len"))
                )
                return
        self.e.error(node, "cannot print a value of this type")

    # control flow --------------------------------------------------------

    def ex_Block(self, node, want=None):
        result = None
        if want not in (None, UNIT, UNKNOWN):
            result = self.new_tmp(want)
        self.push()
        self.open()
        value = self.block_value(node, want)
        if result is not None and value is not None:
            self.line("%s = %s;" % (result, value))
        self.close()
        self.pop()
        return (result if result is not None else "0", want or UNIT)

    def ex_Match(self, node, want=None):
        scrut = f(node, "scrutinee")
        arms = list(f(node, "arms", ()) or ())
        scode, sty = self.expr(scrut)
        ty = want
        if ty in (None, UNKNOWN):
            ty = self.arm_type(arms)
        result = None
        if ty not in (None, UNIT, UNKNOWN):
            result = self.new_tmp(ty)
        tmp = self.new_tmp(sty) if sty not in (None, UNIT, UNKNOWN) else None
        if tmp:
            self.line("%s = %s;" % (tmp, scode))
            scode = tmp

        if sty is not None and sty[0] == "prim" and sty[1] == "bool":
            self.match_bool(node, scode, arms, result, ty)
        elif sty is not None and sty[0] == "named" and self.e.enum_info(sty):
            self.match_enum(node, scode, sty, arms, result, ty)
        else:
            self.match_scalar(node, scode, arms, result, ty)
        return (result if result is not None else "0", ty or UNIT)

    def arm_type(self, arms):
        for arm in arms:
            body = f(arm, "body")
            _code, ty = self.peek(body)
            if ty not in (None, UNIT, UNKNOWN):
                return ty
        return UNIT

    def arm_body(self, arm, result, ty):
        body = f(arm, "body")
        self.push()
        if kind(body) == "Block":
            value = self.block_value(body, ty)
        else:
            value, _t = self.expr(body, ty)
        if result is not None and value is not None:
            self.line("%s = %s;" % (result, value))
        self.pop()

    def match_bool(self, node, scode, arms, result, ty):
        true_arm = false_arm = default = None
        for arm in arms:
            pat = f(arm, "pattern")
            pk = kind(pat)
            if pk == "PatWild":
                default = arm
            elif pk == "PatLit":
                text = str(f(pat, "text", "")).strip()
                if text == "true":
                    true_arm = arm
                elif text == "false":
                    false_arm = arm
            elif pk == "PatVariant":
                name = str(f(pat, "name", ""))
                if name == "true":
                    true_arm = arm
                elif name == "false":
                    false_arm = arm
        true_arm = true_arm or default
        false_arm = false_arm or default
        self.open("if (%s) {" % paren(scode))
        if true_arm is not None:
            self.arm_body(true_arm, result, ty)
        self.close("} else {")
        self.indent += 1
        if false_arm is not None:
            self.arm_body(false_arm, result, ty)
        self.close()

    def match_enum(self, node, scode, sty, arms, result, ty):
        info = self.e.enum_info(sty)
        payloads = dict(info[2])
        self.open("switch (%s.%stag) {" % (paren(scode), GEN))
        for arm in arms:
            pat = f(arm, "pattern")
            pk = kind(pat)
            if pk == "PatWild":
                self.line("default: {")
            elif pk == "PatVariant":
                vname = str(f(pat, "name", ""))
                self.line(
                    "case %s: {" % sym_variant(self.e.variant_parts(sty, vname))
                )
            else:
                self.line("default: {")
                vname = None
            self.indent += 1
            self.push()
            if pk == "PatVariant":
                binder = f(pat, "binder")
                vname = str(f(pat, "name", ""))
                pty = payloads.get(vname)
                if binder and pty is not None:
                    cn = self.declare(str(binder), pty)
                    self.line(
                        "%s = %s.%sdata.%s;"
                        % (
                            self.e.declarator(pty, cn),
                            paren(scode),
                            GEN,
                            sym_member(vname),
                        )
                    )
            self.arm_body(arm, result, ty)
            self.pop()
            self.line("break;")
            self.indent -= 1
            self.line("}")
        if not any(kind(f(a, "pattern")) == "PatWild" for a in arms):
            file, line, col = self.e.pos.of(node)
            self.line(
                "default: %sunreachable(%s, %d, %d);"
                % (GEN, c_string(file.encode("utf-8")), line, col)
            )
        self.close()

    def match_scalar(self, node, scode, arms, result, ty):
        first = True
        for arm in arms:
            pat = f(arm, "pattern")
            pk = kind(pat)
            if pk == "PatWild":
                if first:
                    self.open("{")
                else:
                    self.close("} else {")
                    self.indent += 1
            else:
                text = str(f(pat, "text", f(pat, "name", "0")))
                cond = "%s == %s" % (paren(scode), text)
                if first:
                    self.open("if (%s) {" % cond)
                else:
                    self.close("} else if (%s) {" % cond)
                    self.indent += 1
            self.arm_body(arm, result, ty)
            first = False
        if not first:
            self.close()

    def ex_Try(self, node, want=None):
        """`.try()` -- unwrap Ok, or return the Err/None from this function."""
        operand = f(node, "operand")
        code, ty = self.expr(operand)
        info = self.e.enum_info(ty) if ty is not None and ty[0] == "named" else None
        if info is None:
            self.e.error(node, "`.try()` needs a Res value")
            return (code, ty)
        variants = info[2]
        names = [v for v, _ in variants]
        ok = "Ok" if "Ok" in names else names[0]
        payload = dict(variants).get(ok)
        tmp = self.new_tmp(ty)
        self.line("%s = %s;" % (tmp, code))
        self.open(
            "if (%s.%stag != %s) {"
            % (tmp, GEN, sym_variant(self.e.variant_parts(ty, ok)))
        )
        self.emit_propagate(node, tmp, ty, ok)
        self.close()
        if payload is None:
            return ("0", UNIT)
        return ("%s.%sdata.%s" % (tmp, GEN, sym_member(ok)), payload)

    def emit_propagate(self, node, tmp, ty, ok):
        """Rebuild this function's error variant from the operand's."""
        ret = self.ret
        rinfo = self.e.enum_info(ret) if ret is not None and ret[0] == "named" else None
        if rinfo is None:
            self.e.error(node, "`.try()` requires the enclosing function to return a Res")
            self.line("return;" if self.ret == UNIT else "return (%s){0};" % self.e.ctype(self.ret))
            return
        rnames = [v for v, _ in rinfo[2]]
        rpayloads = dict(rinfo[2])
        source = [v for v, _ in self.e.enum_info(ty)[2] if v != ok]
        target = next((v for v in ("Err", "None") if v in rnames and v in source), None)
        if target is None:
            target = next((v for v in rnames if v != ok), None)
        if target is None:
            self.line("return (%s){0};" % self.e.ctype(ret))
            return
        pty = rpayloads.get(target)
        if pty is None:
            self.line("return %s;" % self.make_variant(ret, target, None))
            return
        src = "%s.%sdata.%s" % (tmp, GEN, sym_member(target))
        sty = dict(self.e.enum_info(ty)[2]).get(target)
        if pty[0] == "union" and sty is not None and sty != pty:
            # error sets merge: wrap the operand's error into this function's
            cname = self.e.ctype(pty)
            wrapped = "((%s){ .%stag = %stag%s, .%sdata = { .%s = %s } })" % (
                cname,
                GEN,
                GEN,
                tcode(sty),
                GEN,
                GEN + "m" + tcode(sty),
                src,
            )
            self.line("return %s;" % self.make_variant(ret, target, wrapped))
            return
        self.line("return %s;" % self.make_variant(ret, target, src))

    def ex_Lambda(self, node, want=None):
        """A non-escaping closure: captured locals by pointer, one C function.

        DESIGN.md's escaping closures need an `Alloc` and are stage 3's
        checker's business; this lowering is correct for the non-escaping case
        the seed subset uses, and the capture record's name is derived from the
        enclosing function's mangled name plus a per-function ordinal, so it is
        a function of the program.
        """
        self.e.error(node, "gen_c does not lower closures yet")
        return ("0", UNKNOWN)

    def ex_FixedArray(self, node, want=None):
        ty = self.e.resolve_type(f(node, "ty"), self.subst, self.parts)
        elems = list(f(node, "elems", ()) or ())
        codes = [self.expr(e, ty[2] if ty[0] == "array" else None)[0] for e in elems]
        cname = self.e.ctype(ty)
        return ("((%s){ { %s } })" % (cname, ", ".join(codes) or "0"), ty)

    def ex_ArrayLit(self, node, want=None):
        elems = list(f(node, "elems", ()) or ())
        elem_ty = want[2] if want is not None and want[0] == "array" else None
        codes = []
        for e in elems:
            code, ety = self.expr(e, elem_ty)
            elem_ty = elem_ty or ety
            codes.append(code)
        ty = ("array", len(elems), elem_ty or prim("i32"))
        cname = self.e.ctype(ty)
        return ("((%s){ { %s } })" % (cname, ", ".join(codes) or "0"), ty)

    def ex_ScopeRef(self, node, want=None):
        self.e.error(node, "`@scope` is not in the seed subset")
        return ("0", UNKNOWN)

    def ex_MetaCall(self, node, want=None):
        self.e.error(node, "`@meta` is not in the seed subset (PLAN.md 0.5)")
        return ("0", UNKNOWN)


ARITH = {"+", "-", "*", "/", "%"}
WRAPPING = {"+%", "-%", "*%"}
COMPARE = {"==", "!=", "<", ">", "<=", ">="}


# ---------------------------------------------------------------------------
# literals and text
# ---------------------------------------------------------------------------


def paren(code):
    if code.isidentifier() or (code.startswith("(") and code.endswith(")")):
        return code
    return "(" + code + ")"


def parse_int(text):
    text = str(text).strip().replace("_", "")
    if not text:
        return 0
    try:
        if text[:2].lower() == "0x":
            return int(text, 16)
        if text[:2].lower() == "0b":
            return int(text, 2)
        if text[:2].lower() == "0o":
            return int(text, 8)
        return int(text, 10)
    except ValueError:
        return 0


def int_literal(value, ty):
    """A C constant that means exactly `value` at exactly `ty`'s width.

    There is no negative literal in C: `-2147483648` is unary minus applied to
    a constant that does not fit an `int`, so the negation happens in a wider
    type.  <stdint.h> spells INT32_MIN `(-2147483647 - 1)`, and so does this.
    Unsigned constants always carry `ULL` -- suffixing by magnitude is exactly
    the bug, because `1` is an `int` and promotes as one.
    """
    name = ty[1] if ty and ty[0] == "prim" else "i32"
    ctype = PRIMS.get(name, "int32_t")
    if name not in INT_VALUES:
        return str(value)
    lo, hi, _bits = INT_VALUES[name]
    signed = lo < 0
    if not signed:
        return "((%s)%dULL)" % (ctype, value & hi)
    if value == lo:
        return "((%s)(-%dLL - 1LL))" % (ctype, -(lo + 1))
    return "((%s)%dLL)" % (ctype, value)


def float_literal(text):
    text = str(text).strip()
    if not text:
        return "0.0"
    if "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return text


_ESCAPES = {
    "n": b"\n",
    "t": b"\t",
    "r": b"\r",
    "0": b"\0",
    "\\": b"\\",
    "'": b"'",
    '"': b'"',
}


def decode_str(text):
    """Source text of a string literal -> its bytes."""
    s = str(text)
    if len(s) >= 2 and s[0] == '"' and s[-1] == '"':
        s = s[1:-1]
    out = bytearray()
    i = 0
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            nxt = s[i + 1]
            if nxt in _ESCAPES:
                out += _ESCAPES[nxt]
                i += 2
                continue
            if nxt == "x" and i + 3 < len(s):
                try:
                    out.append(int(s[i + 2 : i + 4], 16))
                    i += 4
                    continue
                except ValueError:
                    pass
            out += nxt.encode("utf-8")
            i += 2
            continue
        out += c.encode("utf-8")
        i += 1
    return bytes(out)


def decode_char(text):
    s = str(text)
    if len(s) >= 2 and s[0] == "'" and s[-1] == "'":
        s = s[1:-1]
    raw = decode_str('"%s"' % s)
    return raw[0] if raw else 0


def c_string(raw: bytes) -> str:
    """A C string literal.  Octal escapes, so an escape never runs on into the
    next character the way `\\xNN` does, and no hex is emitted at all -- which
    also keeps the determinism scanner's pointer-shaped-hex check quiet."""
    out = ['"']
    for b in raw:
        ch = chr(b)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif 32 <= b < 127:
            out.append(ch)
        else:
            out.append("\\%03o" % b)
    out.append('"')
    return "".join(out)


# ---------------------------------------------------------------------------
# the emitted runtime
# ---------------------------------------------------------------------------

BANNER = """\
/* Generated by the Zen bootstrapper (bootstrap/gen_c.py).  Do not edit.
 *
 * Language: %s.  Compile with -std=c99.
 *
 * This file is deterministic: the same sources produce byte-identical C.
 * It contains no timestamp, no absolute path and no address; every position
 * below is a literal string taken from the AST, relative to the compilation
 * root.  See tests/determinism/README.md.
 *
 * Every identifier derived from Zen source is mangled behind `zu_`, and every
 * identifier this compiler invents is behind `zg_`.  Neither begins with an
 * underscore, so neither collides with the identifiers C11 7.1.3 reserves to
 * the implementation, and no C keyword or standard-header macro can reach the
 * output.  `main` is the one name the C standard fixes.
 */

""" % C_STANDARD

INCLUDES = """\
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

"""

PRELUDE_TYPES = """\
/* ---- runtime ---- */

typedef struct zg_str { const unsigned char *data; size_t len; } zg_str;

/* A trait value is a fat value (DESIGN.md): a receiver plus function
 * pointers, copied by value, never boxed and never allocated. */
typedef struct zg_closure { void *fn; void *env; } zg_closure;

static int zg_argc;
static char **zg_argv;

"""

PRELUDE_TRAP = """\
/* A trap is for a bug (DESIGN.md).  It prints file:line:col and aborts with
 * 134; the position is the operator token.  Note that no check below ever
 * performs the operation first: signed overflow is undefined behaviour in C,
 * and an after-the-fact test is one the optimizer is entitled to delete. */
static void zg_trap(const char *file, unsigned long line, unsigned long col,
                    const char *what) {
    fflush(stdout);
    fprintf(stderr, "%s:%lu:%lu: trap: %s\\n", file, line, col, what);
    fflush(stderr);
    exit(134);
}

static void zg_unreachable(const char *file, unsigned long line,
                           unsigned long col) {
    zg_trap(file, line, col, "unreachable match arm");
}

#if defined(__GNUC__) && (__GNUC__ >= 5)
#define ZG_HAS_OVERFLOW_BUILTINS 1
#elif defined(__has_builtin)
#if __has_builtin(__builtin_add_overflow)
#define ZG_HAS_OVERFLOW_BUILTINS 1
#endif
#endif

static size_t zg_idx_u(uint64_t i, size_t len, const char *file,
                       unsigned long line, unsigned long col) {
    if (i >= (uint64_t)len) zg_trap(file, line, col, "index out of bounds");
    return (size_t)i;
}

static size_t zg_idx_s(int64_t i, size_t len, const char *file,
                       unsigned long line, unsigned long col) {
    if (i < 0 || (uint64_t)i >= (uint64_t)len)
        zg_trap(file, line, col, "index out of bounds");
    return (size_t)i;
}

"""

PRELUDE_PRINT = """\
/* println: std owns this once it exists (DESIGN.md routes it through the Env
 * in scope).  Until then these are the writes gen_c lowers `{}` into: decimal
 * with no separators, and exactly one newline per println. */
static void zg_print_bytes(const char *s, size_t n) { fwrite(s, 1, n, stdout); }
static void zg_print_i64(int64_t v) { fprintf(stdout, "%lld", (long long)v); }
static void zg_print_u64(uint64_t v) { fprintf(stdout, "%llu", (unsigned long long)v); }
static void zg_print_f64(double v) { fprintf(stdout, "%g", v); }
static void zg_print_bool(bool v) { zg_print_bytes(v ? "true" : "false", v ? 4u : 5u); }
static void zg_print_nl(void) { fputc('\\n', stdout); }

"""


def _checked_helpers():
    """One checked helper per (operation, integer type).

    Emitted only for the types a program uses, sorted, so the set never leaks
    an iteration order into the file.
    """
    unsigned_of = {
        "int8_t": "uint8_t",
        "int16_t": "uint16_t",
        "int32_t": "uint32_t",
        "int64_t": "uint64_t",
        "ptrdiff_t": "size_t",
    }
    out = {}
    for name, (signed, bits, cmin, cmax) in sorted(INT_LIMITS.items()):
        ct = PRIMS[name]
        uct = unsigned_of.get(ct, ct)
        cast = "(%s)" % ct
        args = "const char *file, unsigned long line, unsigned long col"
        sig = "static %s zg_%%s_%s(%s a, %s b, %s)" % (ct, name, ct, ct, args)

        if signed:
            add_slow = (
                "    if ((b > 0 && a > %s - b) || (b < 0 && a < %s - b))\n"
                "        zg_trap(file, line, col, \"integer overflow\");\n"
                "    return %s((%s)a + (%s)b);\n" % (cmax, cmin, cast, uct, uct)
            )
            sub_slow = (
                "    if ((b < 0 && a > %s + b) || (b > 0 && a < %s + b))\n"
                "        zg_trap(file, line, col, \"integer overflow\");\n"
                "    return %s((%s)a - (%s)b);\n" % (cmax, cmin, cast, uct, uct)
            )
            mul_slow = (
                "    if (a > 0) {\n"
                "        if (b > 0) { if (a > %s / b) zg_trap(file, line, col, \"integer overflow\"); }\n"
                "        else { if (b < %s / a) zg_trap(file, line, col, \"integer overflow\"); }\n"
                "    } else if (a < 0) {\n"
                "        if (b > 0) { if (a < %s / b) zg_trap(file, line, col, \"integer overflow\"); }\n"
                "        else { if (b < %s / a) zg_trap(file, line, col, \"integer overflow\"); }\n"
                "    }\n"
                "    return %s((%s)a * (%s)b);\n"
                % (cmax, cmin, cmin, cmax, cast, uct, uct)
            )
        else:
            add_slow = (
                "    if (a > %s - b) zg_trap(file, line, col, \"integer overflow\");\n"
                "    return %s(a + b);\n" % (cmax, cast)
            )
            sub_slow = (
                "    if (a < b) zg_trap(file, line, col, \"integer overflow\");\n"
                "    return %s(a - b);\n" % cast
            )
            mul_slow = (
                "    if (b != 0 && a > %s / b) zg_trap(file, line, col, \"integer overflow\");\n"
                "    return %s(a * b);\n" % (cmax, cast)
            )

        for op, builtin, slow in (
            ("add", "__builtin_add_overflow", add_slow),
            ("sub", "__builtin_sub_overflow", sub_slow),
            ("mul", "__builtin_mul_overflow", mul_slow),
        ):
            body = (
                (sig % op)
                + " {\n"
                + "#ifdef ZG_HAS_OVERFLOW_BUILTINS\n"
                + "    %s r;\n" % ct
                + "    if (%s(a, b, &r)) zg_trap(file, line, col, \"integer overflow\");\n" % builtin
                + "    return r;\n"
                + "#else\n"
                + slow
                + "#endif\n}\n\n"
            )
            out["%s_%s" % (op, name)] = body

        div_guard = (
            "    if (b == 0) zg_trap(file, line, col, \"divide by zero\");\n"
        )
        if signed:
            # i32.MIN / -1 is overflow wearing division's clothes, and it
            # faults identically on x86: the message must say overflow.
            div_guard += (
                "    if (a == %s && b == -1) zg_trap(file, line, col, \"integer overflow\");\n"
                % cmin
            )
        out["div_%s" % name] = (sig % "div") + " {\n" + div_guard + "    return %s(a / b);\n}\n\n" % cast
        out["mod_%s" % name] = (sig % "mod") + " {\n" + div_guard + "    return %s(a %% b);\n}\n\n" % cast

        wsig = "static %s zg_%%s_%s(%s a, %s b)" % (ct, name, ct, ct)
        if signed:
            for op, sym in (("wadd", "+"), ("wsub", "-"), ("wmul", "*")):
                out["%s_%s" % (op, name)] = (
                    (wsig % op)
                    + " {\n    return %s((%s)a %s (%s)b);\n}\n\n" % (cast, uct, sym, uct)
                )
        else:
            for op, sym in (("wadd", "+"), ("wsub", "-"), ("wmul", "*")):
                out["%s_%s" % (op, name)] = (
                    (wsig % op) + " {\n    return %s(a %s b);\n}\n\n" % (cast, sym)
                )
    out["idx_u"] = ""  # defined in PRELUDE_TRAP
    out["idx_s"] = ""
    return out


HELPERS = _checked_helpers()


# ---------------------------------------------------------------------------
# the entry point other modules call
# ---------------------------------------------------------------------------


def generate(program, sema=None, root=None, sources=None):
    """The module graph -> (C source text, diagnostics).

    Deterministic: called twice with equal inputs it returns equal strings, and
    it holds no state between calls.
    """
    emitter = Emitter(program, sema=sema, root=root, sources=sources)
    text = emitter.emit()
    return text, tuple(emitter.diags)


# `emit` reads better at a call site that already has a program in hand.
emit = generate
