#!/usr/bin/env python3
"""A commit's subject names its scope, and `src/` obeys it.

Issue #765: af2f9af7 landed three features -- a new LSP code-action provider,
the @meta M0/M1 interception, and a module-resolution change -- inside 113
files under a subject that reads `style:`. Nothing in the message says any of
them happened. A reviewer reading `style:` does not go looking for a new
type-checker interception or a change to module resolution, and git bisect on
any of the three lands on a commit labelled as a formatting sweep.

The rules this gate enforces are the ones the issue asks for and the owner
adopted in the thread:

  1. a commit touching src/ outside its stated scope is rejected at review;
  2. a mechanical sweep lands ALONE -- no feature, no diagnostic change,
     no new file under src/.

THE STATED SCOPE IS THE SUBJECT PREFIX. This repo has written subjects as
`<area>: <fact>` for its whole history (`lex:`, `gen_c:`, `lsp:`, `sema:`),
and multi-area work as a comma list (`gen, lsp:`, `std.text, lsp:`). So the
mechanical form of "outside its stated scope" is decidable:

    every file under src/ that a commit touches must resolve to an area
    named in the subject's prefix.

An area resolves to a path three ways, each taken from the log rather than
invented: a dotted name joins segments (`std.text` is exactly src/std/text/),
a bare name matches any ONE path segment (`lex:` covered src/std/lex/ in
d6882f11; `gen_c:` covers src/gen/gen_c/ without dragging in src/gen/gen.zen),
and a bare name matches the file's own stem (`zen_build.zen` under `zen:`,
because a module's subject file IS the module).

SWEEPS ARE DIFFERENT, and pretending otherwise would have flagged half the
log. `style:`, `fmt:` and `ufcs:` commits reach across every area on purpose
-- that is what a sweep is -- and rule 2 says that is legal IF the sweep lands
alone. Alone is decidable too: a sweep may MODIFY src/, but it may not ADD a
file under src/ (a new file is a feature landing, rule 3's own sentence) and
it may not add or change any `.expected` / `.count` file (the corpus speaks
in those; a diff in them is a behaviour or diagnostic change). Applied to the
history: 3a976841 and 35efd2ee and 90921493 were sweeps and landed alone --
they pass. af2f9af7 declared `style:` and added src/lsp/lsp_action.zen and
changed nine `.expected` files -- it fails both ways at once, which is the
issue's point made mechanical.

A subject with NO `<areas>:` prefix (`fix-c06`, `wip: ...`, a bare sentence)
states no scope, so any src/ touch is outside it. That refusal IS rule 1: a
commit that cannot say where it reaches must not reach. Merge commits are
skipped -- their parents state the scopes, and a diff against both parents
double-counts everything the branches shared.

WHY THE SUBJECT AND NOT A TRAILER. A trailer (`Scope:`) duplicates a fact the
subject already carries, and two copies of a fact is one stale fact waiting
to happen -- the same argument STYLE.md makes about restating rules. It also
lets the message and the trailer disagree, which is worse than either alone.

WHAT IS DELIBERATELY NOT CHECKED, because gating it would be guessing:
  - whether the subject's FACT is true of the files (judgement, review);
  - tests/, docs/, Makefile, ISSUES.md riding along. Every lane here commits
    its proof beside its change -- 1aab00ca adds four corpus files under
    `gen_c:`, d6882f11 adds must-fails and a gate under `lex:` -- so a rule
    that made tests need their own sentence would be violated by every good
    commit in the log. The owner's rule targets src/; only inside a SWEEP do
    expectation files count, because there they are the evidence of a hidden
    second landing.
  - seed/zen.c. It is a build artifact regenerated by `make seed`, which the
    Makefile runs `git add` on; five recent commits are nothing else. It
    carries no information about scope, so it is exempt everywhere.

EXIT CODES follow the house convention (STYLE.md): 0 pass, 1 violation found,
2 the harness could not run -- checked nothing, never counted as a pass.

SELF-TEST. `--self-test` runs the fixture table below and exits nonzero on
any disagreement. `make scope` runs it before the real audit, so the gate
cannot quietly rot: a parser change that starts misreading subjects fails
the target even when the tree itself is clean.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# THE BUILD ARTIFACT EXEMPTION. `make seed` regenerates seed/zen.c from the
# tree and `git add`s it; it is emitted bytes, not authored scope.
EXEMPT_PREFIXES = ("seed/",)

# THE MECHANICAL-SWEEP TAGS, as used in this repo's log. A commit under one
# of these prefixes DECLARES itself a sweep and gets rule 2 instead of rule
# 1: src/ may be rewritten anywhere, but the landing must be alone.
SWEEP_TAGS = {"style", "fmt", "format", "ufcs"}

# What a sweep may not bring with it: new code (rule 3 gives a new src/ file
# its own sentence) and expectation diffs (a diagnostic or behaviour change).
SWEEP_FORBIDDEN_SUFFIXES = (".expected", ".count")

SUBJECT_RE = re.compile(r"^(?P<areas>[A-Za-z0-9_., +\-]+?): (?P<fact>.+)$")


def parse_areas(subject: str) -> list[str] | None:
    """The areas a subject declares, or None when it declares none.

    None covers: no `<areas>:` shape at all, an empty area list, duplicate
    areas (`gen, gen:` scopes nothing coherent). Callers treat None as
    "nothing is scoped".
    """
    m = SUBJECT_RE.match(subject)
    if m is None:
        return None
    areas = [a.strip().lower() for a in m.group("areas").split(",")]
    if not all(areas) or len(areas) != len(set(areas)):
        return None
    return areas


def is_sweep(subject: str) -> bool:
    areas = parse_areas(subject)
    return areas is not None and len(areas) == 1 and areas[0] in SWEEP_TAGS


def area_matches(area: str, rel: str) -> bool:
    """Does one declared area cover one src/-relative path? See module doc."""
    parts = rel.split("/")
    dotted = area.split(".")
    if parts[: len(dotted)] == dotted and len(parts) > len(dotted):
        return True
    if area in parts[:-1]:  # any single directory segment
        return True
    return parts[-1][: -len(".zen")] == area  # the module's own stem


def scoped_out(subject: str, changes: dict[str, str]) -> list[str]:
    """src/ files this commit touches outside whatever its subject scopes."""
    areas = parse_areas(subject)
    out = []
    for p, _status in sorted(changes.items()):
        if not p.startswith("src/") or p.startswith(EXEMPT_PREFIXES):
            continue
        if areas is None or not any(area_matches(a, p[len("src/"):])
                                    for a in areas):
            out.append(p)
    return out


def sweep_contraband(changes: dict[str, str]) -> list[str]:
    """What rule 2 forbids a sweep to carry: new src/ files, expect diffs."""
    bad = []
    for p, status in sorted(changes.items()):
        if p.startswith(EXEMPT_PREFIXES):
            continue
        if p.startswith("src/") and status == "A":
            bad.append(f"{p} (added inside a sweep)")
        elif p.endswith(SWEEP_FORBIDDEN_SUFFIXES) and status in "AM":
            bad.append(f"{p} (expectation changed inside a sweep)")
    return bad


def violations_for(subject: str, changes: dict[str, str]) -> list[str]:
    if is_sweep(subject):
        return sweep_contraband(changes)
    return scoped_out(subject, changes)


# ---------------------------------------------------------------------------
# SELF-TEST FIXTURES. Each row: (subject, {path: status}, EXPECT VIOLATION?,
# why). Green shapes occur throughout the log and must stay legal; red ones
# are the failure the rule exists for and near misses that must not slip by.
# ---------------------------------------------------------------------------
CASES = [
    # --- shapes from the log that must stay GREEN -------------------------
    ("lex: a backslash before a newline is not a line continuation",
     {"ISSUES.md": "M", "Makefile": "M", "src/std/lex/lex_literal.zen": "M",
      "tests/must-fail/lex/string_backslash_before_newline.zen": "A"}, False,
     "single area; a segment match covers src/std/lex; tests ride along"),
    ("gen, lsp: five duplicate functions collapsed",
     {"src/gen/gen_c/gen_c_build.zen": "M",
      "src/lsp/lsp_names.zen": "M"}, False,
     "comma list covers both folders"),
    ("std.text, lsp: a width, matched once",
     {"src/std/text/text_utf8.zen": "M",
      "src/lsp/lsp_json_read.zen": "M"}, False,
     "dotted area resolves to src/std/text"),
    ("ufcs: a gate on two free functions sharing a name AND a receiver (#722)",
     {"scripts/ufcs_collisions.py": "M", "seed/zen.c": "M",
      "src/sema/sema_member.zen": "M",
      "src/gen/gen_c/gen_c_array.zen": "M"}, False,
     "a DECLARED sweep may rewrite src/ anywhere -- and this one added"
     " nothing under src/ and touched no expectations"),
    ("zen: where the compiler's bytes go is its own file, not the build's",
     {"seed/zen.c": "M", "src/zen/zen_write.zen": "A",
      "src/zen/zen_cli.zen": "M"}, False,
     "seed/ exempt everywhere; a feature may add files INSIDE its area;"
     " stem match covers zen_* files"),
    ("std: one sort, because the second hand-copy is what moves a thing into std",
     {"src/std/collections/collections_sort.zen": "A",
      "src/lsp/lsp_colour.zen": "M",
      "src/lsp/lsp_compl.zen": "M"}, True,
     "the real 5fb3992e. Under the adopted rule it should have been"
     " `std, lsp: one sort` -- one comma in the subject. Kept RED on purpose:"
     " this is the boundary case the rule draws, not noise the gate waves"
     " through"),
    ("ISSUES: five verified findings from a 160-lane bug hunt",
     {"ISSUES.md": "M"}, False,
     "no src/ touched, so no scope needed"),
    ("gitignore: zen-new.c is a build artifact, not a source file",
     {".gitignore": "M", "seed/zen.c": "D"}, False,
     "dotfile subject with no src/ touch"),
    # --- the failure the rule exists for ---------------------------------
    ("style: half the UFCS debt is paid, and the ledger says what the tree says",
     {"docs/design_json.md": "A", "scripts/style.py": "M",
      "seed/zen.c": "M", "src/fmt/fmt_break.zen": "M",
      "src/lsp/lsp_action.zen": "A", "src/sema/sema_meta.zen": "M",
      "src/zen/zen_build.zen": "M",
      "tests/corpus/lsp/a_missing_module_is_named/main.expected": "M"}, True,
     "THE ISSUE #765 SHAPE: `style:` sweep that ADDED lsp_action.zen and"
     " rewrote nine expectations -- three features inside a format sweep"),
    ("style: reflow comments only", {"src/sema/sema_type.zen": "M",
                                     "docs/STYLE.md": "M"}, False,
     "an honest sweep: modifies src/, adds nothing, touches no expectations"),
    ("zen: regenerate everything", {"src/gen/gen_c/gen_c_expr.zen": "M"}, True,
     "`zen:` does not own gen_c -- segment matching, not string prefixing"),
    ("sema: tighten the checker", {"src/sema/sema_type.zen": "M",
                                   "src/zen/zen_cli.zen": "M"}, True,
     "one area named, another reached"),
    ("gen_c, lsp: rewrite the writers",
     {"src/gen/gen_c/gen_c_call.zen": "M", "src/lsp/lsp_fmt.zen": "M",
      "src/fmt/fmt_src.zen": "M"}, True,
     "named areas hold, fmt is outside them"),
    ("wip: half the tree reordered", {"src/sema/sema_type.zen": "M"}, True,
     "`wip:` states no scope, so any src/ touch is outside it"),
    # --- grammar edges ----------------------------------------------------
    ("no colon anywhere in this one", {"src/std/core/display.zen": "M"}, True,
     "no `<areas>:` prefix -> nothing scoped -> src/ refuses"),
    ("a, b, c", {}, False,
     "empty fact still parses as areas; nothing under src/, so passes"),
    ("gen, gen: twice", {"src/gen/gen.zen": "M"}, True,
     "duplicate areas are malformed, so the prefix scopes nothing"),
]


def self_test() -> int:
    bad = 0
    for subject, changes, expect_bad, why in CASES:
        got = violations_for(subject, changes)
        ok = bool(got) == expect_bad
        mark = "ok:   " if ok else "FAIL: "
        print(f"self-test {mark}{subject!r}")
        if not ok:
            print(f"    {why}")
            verdict = f"{len(got)} finding(s): {got}" if got else "PASS"
            print(f"    expected {'VIOLATION' if expect_bad else 'PASS'},"
                  f" got {verdict}")
            bad += 1
    n = len(CASES)
    if bad:
        print(f"\nscope: self-test {bad}/{n} case(s) disagree")
        return 1
    print(f"\nscope: self-test {n}/{n} cases agree")
    return 0


# ---------------------------------------------------------------------------
def changed_files(rev: str) -> tuple[dict[str, str], bool] | None:
    """({path: status}, is_merge) for one commit, via plumbing interfaces."""
    out = subprocess.run(
        ["git", "-C", str(ROOT), "diff-tree", "-r", "--name-status",
         "--root", "--no-commit-id", rev],
        capture_output=True, text=True)
    if out.returncode != 0:
        print(f"scope: could not read {rev}: {out.stderr.strip()}",
              file=sys.stderr)
        return None
    changes: dict[str, str] = {}
    for ln in out.stdout.splitlines():
        if not ln.strip():
            continue
        status, path = ln.split("\t", 1)
        if "\t" in path:  # R100 old new -- the NEW name is what landed
            path = path.split("\t")[-1]
        changes[path] = status[0]
    heads = subprocess.run(
        ["git", "-C", str(ROOT), "rev-list", "--parents", "-n", "1", rev],
        capture_output=True, text=True)
    is_merge = heads.returncode == 0 and len(heads.stdout.split()) > 2
    return changes, is_merge


def commit_subject(rev: str) -> str | None:
    out = subprocess.run(
        ["git", "-C", str(ROOT), "log", "-1", "--format=%s", rev],
        capture_output=True, text=True)
    if out.returncode != 0:
        return None
    return out.stdout.strip()


def main(argv: list[str]) -> int:
    if "--self-test" in argv:
        return self_test()

    revs = [a for a in argv if not a.startswith("-")]
    if not revs:
        revs = ["HEAD"]

    audited = 0
    failures = 0
    for rev in revs:
        subject = commit_subject(rev)
        got = changed_files(rev)
        if subject is None or got is None:
            print(f"scope: could not read {rev}; checked nothing",
                  file=sys.stderr)
            return 2
        changes, is_merge = got
        if is_merge:
            print(f"{rev} MERGE {subject!r} skipped -- parents state the scopes")
            continue
        audited += 1

        found = violations_for(subject, changes)
        print(f"{rev} {'OK' if not found else 'VIOLATION'} {subject!r}")
        for f in found[:12]:
            print(f"    {f}")
        if len(found) > 12:
            print(f"    .. and {len(found) - 12} more")
        failures += bool(found)

    if failures:
        print(f"\nscope: {failures} of {audited} audited commit(s) break the"
              f" scope rules (issue #765).")
        print("  1. a commit touching src/ outside its stated scope is"
              " rejected at review:")
        print("       state the area in the subject -- `<area>, <area>:"
              " <fact>`.")
        print("  2. a mechanical sweep (`style:`/`fmt:`/`ufcs:`) lands alone:"
              " no new file")
        print("       under src/, no `.expected`/`.count` change -- that is a"
              " feature and")
        print("       gets its own commit and its own sentence.")
        return 1
    print(f"\nscope: {audited} commit(s) audited; every src/ touch is inside"
          f" its subject's stated scope")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
