#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 151
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 16

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_LBRACE = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACE = 5,
  anon_sym_EQ = 6,
  anon_sym_DOT = 7,
  anon_sym_pub = 8,
  anon_sym_COLON = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_i32 = 12,
  anon_sym_i64 = 13,
  anon_sym_bool = 14,
  anon_sym_void = 15,
  anon_sym_Ptr = 16,
  anon_sym_MutPtr = 17,
  anon_sym_RawPtr = 18,
  anon_sym_LT = 19,
  anon_sym_GT = 20,
  anon_sym_PLUS = 21,
  anon_sym_DASH = 22,
  anon_sym_STAR = 23,
  sym_integer = 24,
  sym_string = 25,
  sym_source_file = 26,
  sym__item = 27,
  sym_import = 28,
  sym_module_path = 29,
  sym_struct = 30,
  sym_field = 31,
  sym_enum = 32,
  sym_variant = 33,
  sym_function = 34,
  sym_param = 35,
  sym__type = 36,
  sym_primitive = 37,
  sym_pointer = 38,
  sym_named_type = 39,
  sym_block = 40,
  sym__statement = 41,
  sym_enum_ctor = 42,
  sym__expression = 43,
  sym__unary = 44,
  sym__primary = 45,
  sym_call = 46,
  sym_field_access = 47,
  sym_binary = 48,
  sym_struct_literal = 49,
  sym_field_init = 50,
  sym_parenthesized = 51,
  sym_arguments = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_import_repeat1 = 54,
  aux_sym_module_path_repeat1 = 55,
  aux_sym_struct_repeat1 = 56,
  aux_sym_enum_repeat1 = 57,
  aux_sym_function_repeat1 = 58,
  aux_sym_named_type_repeat1 = 59,
  aux_sym_block_repeat1 = 60,
  aux_sym_struct_literal_repeat1 = 61,
  aux_sym_arguments_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_pub] = "pub",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_i32] = "i32",
  [anon_sym_i64] = "i64",
  [anon_sym_bool] = "bool",
  [anon_sym_void] = "void",
  [anon_sym_Ptr] = "Ptr",
  [anon_sym_MutPtr] = "MutPtr",
  [anon_sym_RawPtr] = "RawPtr",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [sym_integer] = "integer",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_import] = "import",
  [sym_module_path] = "module_path",
  [sym_struct] = "struct",
  [sym_field] = "field",
  [sym_enum] = "enum",
  [sym_variant] = "variant",
  [sym_function] = "function",
  [sym_param] = "param",
  [sym__type] = "_type",
  [sym_primitive] = "primitive",
  [sym_pointer] = "pointer",
  [sym_named_type] = "named_type",
  [sym_block] = "block",
  [sym__statement] = "_statement",
  [sym_enum_ctor] = "enum_ctor",
  [sym__expression] = "_expression",
  [sym__unary] = "_unary",
  [sym__primary] = "_primary",
  [sym_call] = "call",
  [sym_field_access] = "field_access",
  [sym_binary] = "binary",
  [sym_struct_literal] = "struct_literal",
  [sym_field_init] = "field_init",
  [sym_parenthesized] = "parenthesized",
  [sym_arguments] = "arguments",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_import_repeat1] = "import_repeat1",
  [aux_sym_module_path_repeat1] = "module_path_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
  [aux_sym_enum_repeat1] = "enum_repeat1",
  [aux_sym_function_repeat1] = "function_repeat1",
  [aux_sym_named_type_repeat1] = "named_type_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_struct_literal_repeat1] = "struct_literal_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_pub] = anon_sym_pub,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_Ptr] = anon_sym_Ptr,
  [anon_sym_MutPtr] = anon_sym_MutPtr,
  [anon_sym_RawPtr] = anon_sym_RawPtr,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_integer] = sym_integer,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_import] = sym_import,
  [sym_module_path] = sym_module_path,
  [sym_struct] = sym_struct,
  [sym_field] = sym_field,
  [sym_enum] = sym_enum,
  [sym_variant] = sym_variant,
  [sym_function] = sym_function,
  [sym_param] = sym_param,
  [sym__type] = sym__type,
  [sym_primitive] = sym_primitive,
  [sym_pointer] = sym_pointer,
  [sym_named_type] = sym_named_type,
  [sym_block] = sym_block,
  [sym__statement] = sym__statement,
  [sym_enum_ctor] = sym_enum_ctor,
  [sym__expression] = sym__expression,
  [sym__unary] = sym__unary,
  [sym__primary] = sym__primary,
  [sym_call] = sym_call,
  [sym_field_access] = sym_field_access,
  [sym_binary] = sym_binary,
  [sym_struct_literal] = sym_struct_literal,
  [sym_field_init] = sym_field_init,
  [sym_parenthesized] = sym_parenthesized,
  [sym_arguments] = sym_arguments,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_import_repeat1] = aux_sym_import_repeat1,
  [aux_sym_module_path_repeat1] = aux_sym_module_path_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
  [aux_sym_enum_repeat1] = aux_sym_enum_repeat1,
  [aux_sym_function_repeat1] = aux_sym_function_repeat1,
  [aux_sym_named_type_repeat1] = aux_sym_named_type_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_struct_literal_repeat1] = aux_sym_struct_literal_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Ptr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MutPtr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RawPtr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_module_path] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [sym_pointer] = {
    .visible = true,
    .named = true,
  },
  [sym_named_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_enum_ctor] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__unary] = {
    .visible = false,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_field_access] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_field_init] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_named_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_dir = 2,
  field_fn = 3,
  field_name = 4,
  field_obj = 5,
  field_payload = 6,
  field_pointee = 7,
  field_ret = 8,
  field_type = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_dir] = "dir",
  [field_fn] = "fn",
  [field_name] = "name",
  [field_obj] = "obj",
  [field_payload] = "payload",
  [field_pointee] = "pointee",
  [field_ret] = "ret",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 3},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 3},
  [7] = {.index = 12, .length = 3},
  [8] = {.index = 15, .length = 3},
  [9] = {.index = 18, .length = 2},
  [10] = {.index = 20, .length = 1},
  [11] = {.index = 21, .length = 3},
  [12] = {.index = 24, .length = 3},
  [13] = {.index = 27, .length = 1},
  [14] = {.index = 28, .length = 2},
  [15] = {.index = 30, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_body, 5},
    {field_name, 0},
    {field_ret, 4},
  [5] =
    {field_name, 0},
    {field_type, 2},
  [7] =
    {field_name, 0},
    {field_payload, 2},
  [9] =
    {field_body, 6},
    {field_name, 1},
    {field_ret, 5},
  [12] =
    {field_body, 6},
    {field_name, 0},
    {field_ret, 5},
  [15] =
    {field_body, 7},
    {field_name, 1},
    {field_ret, 6},
  [18] =
    {field_dir, 0},
    {field_pointee, 2},
  [20] =
    {field_fn, 0},
  [21] =
    {field_body, 7},
    {field_name, 0},
    {field_ret, 6},
  [24] =
    {field_body, 8},
    {field_name, 1},
    {field_ret, 7},
  [27] =
    {field_type, 0},
  [28] =
    {field_name, 2},
    {field_obj, 0},
  [30] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '"', 1,
        '(', 12,
        ')', 13,
        '*', 18,
        '+', 16,
        ',', 7,
        '-', 17,
        '.', 10,
        '/', 2,
        ':', 11,
        '<', 14,
        '=', 9,
        '>', 15,
        '@', 3,
        '{', 6,
        '}', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 3:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'M') ADVANCE(1);
      if (lookahead == 'P') ADVANCE(2);
      if (lookahead == 'R') ADVANCE(3);
      if (lookahead == 'b') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == 'p') ADVANCE(6);
      if (lookahead == 'v') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == '3') ADVANCE(12);
      if (lookahead == '6') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'w') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == '2') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == '4') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 'b') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'P') ADVANCE(24);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_Ptr);
      END_STATE();
    case 18:
      if (lookahead == 'P') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_pub);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_void);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_MutPtr);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RawPtr);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_pub] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_Ptr] = ACTIONS(1),
    [anon_sym_MutPtr] = ACTIONS(1),
    [anon_sym_RawPtr] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(146),
    [sym__item] = STATE(38),
    [sym_import] = STATE(38),
    [sym_struct] = STATE(38),
    [sym_enum] = STATE(38),
    [sym_function] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(38),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_pub] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(16), 1,
      anon_sym_RBRACE,
    ACTIONS(18), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(24), 2,
      sym_integer,
      sym_string,
    STATE(39), 2,
      sym__expression,
      sym_binary,
    STATE(2), 3,
      sym__statement,
      sym_enum_ctor,
      aux_sym_block_repeat1,
    STATE(21), 6,
      sym__unary,
      sym__primary,
      sym_call,
      sym_field_access,
      sym_struct_literal,
      sym_parenthesized,
  [37] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      anon_sym_DOT,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      sym_integer,
      sym_string,
    STATE(39), 2,
      sym__expression,
      sym_binary,
    STATE(4), 3,
      sym__statement,
      sym_enum_ctor,
      aux_sym_block_repeat1,
    STATE(21), 6,
      sym__unary,
      sym__primary,
      sym_call,
      sym_field_access,
      sym_struct_literal,
      sym_parenthesized,
  [74] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_DOT,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 2,
      sym_integer,
      sym_string,
    STATE(39), 2,
      sym__expression,
      sym_binary,
    STATE(2), 3,
      sym__statement,
      sym_enum_ctor,
      aux_sym_block_repeat1,
    STATE(21), 6,
      sym__unary,
      sym__primary,
      sym_call,
      sym_field_access,
      sym_struct_literal,
      sym_parenthesized,
  [111] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_RPAREN,
    ACTIONS(35), 2,
      sym_integer,
      sym_string,
    STATE(48), 2,
      sym__expression,
      sym_binary,
    STATE(21), 6,
      sym__unary,
      sym__primary,
      sym_call,
      sym_field_access,
      sym_struct_literal,
      sym_parenthesized,
  [140] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      sym_integer,
      sym_string,
    STATE(61), 2,
      sym__expression,
      sym_binary,
    STATE(21), 6,
      sym__unary,
      sym__primary,
      sym_call,
      sym_field_access,
      sym_struct_literal,
      sym_parenthesized,
  [166] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(123), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [190] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(90), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [214] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(138), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [238] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(133), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [262] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      sym_integer,
      sym_string,
    STATE(52), 2,
      sym__expression,
      sym_binary,
    STATE(21), 6,
      sym__unary,
      sym__primary,
      sym_call,
      sym_field_access,
      sym_struct_literal,
      sym_parenthesized,
  [288] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(144), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [312] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(121), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [336] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      sym_integer,
      sym_string,
    STATE(59), 2,
      sym__expression,
      sym_binary,
    STATE(21), 6,
      sym__unary,
      sym__primary,
      sym_call,
      sym_field_access,
      sym_struct_literal,
      sym_parenthesized,
  [362] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(131), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [386] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(130), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [410] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(118), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [434] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(117), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [458] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(120), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [482] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [502] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    STATE(29), 1,
      sym_arguments,
    ACTIONS(51), 9,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [526] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(45), 3,
      anon_sym_Ptr,
      anon_sym_MutPtr,
      anon_sym_RawPtr,
    ACTIONS(43), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_void,
    STATE(115), 4,
      sym__type,
      sym_primitive,
      sym_pointer,
      sym_named_type,
  [550] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      sym_integer,
      sym_string,
    STATE(35), 2,
      sym__expression,
      sym_binary,
    STATE(21), 6,
      sym__unary,
      sym__primary,
      sym_call,
      sym_field_access,
      sym_struct_literal,
      sym_parenthesized,
  [576] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 2,
      sym_integer,
      sym_string,
    STATE(36), 2,
      sym__expression,
      sym_binary,
    STATE(21), 6,
      sym__unary,
      sym__primary,
      sym_call,
      sym_field_access,
      sym_struct_literal,
      sym_parenthesized,
  [602] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [619] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [670] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [687] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [704] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [721] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [738] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [755] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [772] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 11,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_integer,
      sym_string,
      sym_identifier,
  [789] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(77), 10,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_integer,
      sym_string,
      sym_identifier,
  [808] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(89), 1,
      anon_sym_pub,
    STATE(37), 6,
      sym__item,
      sym_import,
      sym_struct,
      sym_enum,
      sym_function,
      aux_sym_source_file_repeat1,
  [832] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_pub,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    STATE(37), 6,
      sym__item,
      sym_import,
      sym_struct,
      sym_enum,
      sym_function,
      aux_sym_source_file_repeat1,
  [856] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(96), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 6,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      sym_integer,
      sym_string,
      sym_identifier,
  [875] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_enum_repeat1,
    ACTIONS(98), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(100), 2,
      anon_sym_pub,
      sym_identifier,
  [893] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym_enum_repeat1,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(106), 2,
      anon_sym_pub,
      sym_identifier,
  [911] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
    ACTIONS(110), 2,
      anon_sym_pub,
      sym_identifier,
    ACTIONS(108), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
  [927] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_LT,
    ACTIONS(114), 5,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_GT,
  [941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 6,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      sym_integer,
      sym_string,
      sym_identifier,
  [953] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_DOT,
    STATE(51), 1,
      aux_sym_module_path_repeat1,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(122), 2,
      anon_sym_pub,
      sym_identifier,
  [971] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_DOT,
    STATE(46), 1,
      aux_sym_module_path_repeat1,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(128), 2,
      anon_sym_pub,
      sym_identifier,
  [989] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_enum_repeat1,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(135), 2,
      anon_sym_pub,
      sym_identifier,
  [1007] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_arguments_repeat1,
    ACTIONS(96), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1027] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_enum_repeat1,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(143), 2,
      anon_sym_pub,
      sym_identifier,
  [1045] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_enum_repeat1,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(147), 2,
      anon_sym_pub,
      sym_identifier,
  [1063] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_DOT,
    STATE(46), 1,
      aux_sym_module_path_repeat1,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(154), 2,
      anon_sym_pub,
      sym_identifier,
  [1081] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(96), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(156), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1096] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 5,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_GT,
  [1107] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 5,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_GT,
  [1118] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 5,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_GT,
  [1129] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 2,
      anon_sym_pub,
      sym_identifier,
    ACTIONS(164), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
  [1142] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 2,
      anon_sym_pub,
      sym_identifier,
    ACTIONS(126), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DOT,
  [1155] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      anon_sym_pub,
      sym_identifier,
    ACTIONS(145), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
  [1168] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(96), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(168), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1183] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 5,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_GT,
  [1194] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    ACTIONS(96), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1208] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(176), 2,
      anon_sym_pub,
      sym_identifier,
  [1220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(180), 2,
      anon_sym_pub,
      sym_identifier,
  [1232] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(184), 2,
      anon_sym_pub,
      sym_identifier,
  [1244] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(188), 2,
      anon_sym_pub,
      sym_identifier,
  [1256] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(192), 2,
      anon_sym_pub,
      sym_identifier,
  [1268] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(196), 2,
      anon_sym_pub,
      sym_identifier,
  [1280] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(200), 2,
      anon_sym_pub,
      sym_identifier,
  [1292] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(204), 2,
      anon_sym_pub,
      sym_identifier,
  [1304] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(208), 2,
      anon_sym_pub,
      sym_identifier,
  [1316] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(212), 2,
      anon_sym_pub,
      sym_identifier,
  [1328] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(216), 2,
      anon_sym_pub,
      sym_identifier,
  [1340] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(220), 2,
      anon_sym_pub,
      sym_identifier,
  [1352] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(224), 2,
      anon_sym_pub,
      sym_identifier,
  [1364] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(228), 2,
      anon_sym_pub,
      sym_identifier,
  [1376] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(232), 2,
      anon_sym_pub,
      sym_identifier,
  [1388] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(236), 2,
      anon_sym_pub,
      sym_identifier,
  [1400] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_identifier,
    ACTIONS(240), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_variant,
  [1413] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(245), 1,
      anon_sym_GT,
    STATE(79), 1,
      aux_sym_named_type_repeat1,
  [1426] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym_identifier,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
    STATE(122), 1,
      sym_field_init,
  [1439] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(253), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      sym_field,
  [1452] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      aux_sym_struct_repeat1,
  [1465] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      aux_sym_import_repeat1,
  [1478] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(264), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      sym_field,
  [1491] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_identifier,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      sym_variant,
  [1504] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym_function_repeat1,
  [1517] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    STATE(87), 1,
      aux_sym_arguments_repeat1,
  [1530] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(275), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      sym_field,
  [1543] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_identifier,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      sym_param,
  [1556] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    ACTIONS(283), 1,
      anon_sym_GT,
    STATE(107), 1,
      aux_sym_named_type_repeat1,
  [1569] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_COMMA,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym_function_repeat1,
  [1582] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
    STATE(93), 1,
      aux_sym_struct_literal_repeat1,
  [1595] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    STATE(106), 1,
      aux_sym_struct_literal_repeat1,
  [1608] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    ACTIONS(299), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      aux_sym_import_repeat1,
  [1621] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(301), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_function_repeat1,
  [1634] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_COMMA,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      aux_sym_struct_repeat1,
  [1647] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    STATE(103), 1,
      aux_sym_function_repeat1,
  [1660] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_arguments_repeat1,
  [1673] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    ACTIONS(311), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      aux_sym_import_repeat1,
  [1686] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_COMMA,
    ACTIONS(315), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      aux_sym_struct_repeat1,
  [1699] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_identifier,
    ACTIONS(317), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      sym_param,
  [1712] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(315), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      sym_field,
  [1725] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym_function_repeat1,
  [1738] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym_identifier,
    ACTIONS(321), 1,
      anon_sym_RBRACE,
    STATE(122), 1,
      sym_field_init,
  [1751] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_RBRACE,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    STATE(82), 1,
      aux_sym_struct_repeat1,
  [1764] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_COMMA,
    ACTIONS(328), 1,
      anon_sym_RBRACE,
    STATE(106), 1,
      aux_sym_struct_literal_repeat1,
  [1777] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    ACTIONS(330), 1,
      anon_sym_GT,
    STATE(79), 1,
      aux_sym_named_type_repeat1,
  [1790] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      anon_sym_COMMA,
    ACTIONS(334), 1,
      anon_sym_RBRACE,
    STATE(105), 1,
      aux_sym_struct_repeat1,
  [1803] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym_identifier,
    ACTIONS(336), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_field_init,
  [1816] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym_identifier,
    STATE(65), 1,
      sym_module_path,
  [1826] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      anon_sym_EQ,
    ACTIONS(342), 1,
      anon_sym_COLON,
  [1836] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym_identifier,
    STATE(122), 1,
      sym_field_init,
  [1846] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_identifier,
    STATE(58), 1,
      sym_variant,
  [1856] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      anon_sym_EQ,
    ACTIONS(346), 1,
      anon_sym_COLON,
  [1866] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_LBRACE,
    STATE(76), 1,
      sym_block,
  [1876] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    STATE(96), 1,
      sym_field,
  [1886] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1894] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_LBRACE,
    STATE(73), 1,
      sym_block,
  [1904] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    STATE(132), 1,
      sym_field,
  [1914] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_LBRACE,
    STATE(70), 1,
      sym_block,
  [1924] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1932] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1940] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      sym_block,
  [1950] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1958] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym_identifier,
    STATE(63), 1,
      sym_module_path,
  [1968] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1976] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    STATE(44), 1,
      sym_arguments,
  [1986] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_identifier,
    STATE(124), 1,
      sym_param,
  [1996] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    STATE(108), 1,
      sym_field,
  [2006] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_LBRACE,
    STATE(72), 1,
      sym_block,
  [2016] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2024] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2032] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_LBRACE,
    STATE(67), 1,
      sym_block,
  [2042] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 1,
      anon_sym_EQ,
  [2049] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(356), 1,
      sym_identifier,
  [2056] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(358), 1,
      sym_identifier,
  [2063] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      anon_sym_LPAREN,
  [2070] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(362), 1,
      anon_sym_GT,
  [2077] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(364), 1,
      anon_sym_LPAREN,
  [2084] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 1,
      sym_identifier,
  [2091] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 1,
      anon_sym_COLON,
  [2098] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 1,
      anon_sym_EQ,
  [2105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(372), 1,
      anon_sym_LT,
  [2112] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      anon_sym_RPAREN,
  [2119] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(376), 1,
      anon_sym_COLON,
  [2126] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(378), 1,
      ts_builtin_sym_end,
  [2133] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(380), 1,
      sym_identifier,
  [2140] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      sym_identifier,
  [2147] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 1,
      sym_identifier,
  [2154] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(386), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 140,
  [SMALL_STATE(7)] = 166,
  [SMALL_STATE(8)] = 190,
  [SMALL_STATE(9)] = 214,
  [SMALL_STATE(10)] = 238,
  [SMALL_STATE(11)] = 262,
  [SMALL_STATE(12)] = 288,
  [SMALL_STATE(13)] = 312,
  [SMALL_STATE(14)] = 336,
  [SMALL_STATE(15)] = 362,
  [SMALL_STATE(16)] = 386,
  [SMALL_STATE(17)] = 410,
  [SMALL_STATE(18)] = 434,
  [SMALL_STATE(19)] = 458,
  [SMALL_STATE(20)] = 482,
  [SMALL_STATE(21)] = 502,
  [SMALL_STATE(22)] = 526,
  [SMALL_STATE(23)] = 550,
  [SMALL_STATE(24)] = 576,
  [SMALL_STATE(25)] = 602,
  [SMALL_STATE(26)] = 619,
  [SMALL_STATE(27)] = 636,
  [SMALL_STATE(28)] = 653,
  [SMALL_STATE(29)] = 670,
  [SMALL_STATE(30)] = 687,
  [SMALL_STATE(31)] = 704,
  [SMALL_STATE(32)] = 721,
  [SMALL_STATE(33)] = 738,
  [SMALL_STATE(34)] = 755,
  [SMALL_STATE(35)] = 772,
  [SMALL_STATE(36)] = 789,
  [SMALL_STATE(37)] = 808,
  [SMALL_STATE(38)] = 832,
  [SMALL_STATE(39)] = 856,
  [SMALL_STATE(40)] = 875,
  [SMALL_STATE(41)] = 893,
  [SMALL_STATE(42)] = 911,
  [SMALL_STATE(43)] = 927,
  [SMALL_STATE(44)] = 941,
  [SMALL_STATE(45)] = 953,
  [SMALL_STATE(46)] = 971,
  [SMALL_STATE(47)] = 989,
  [SMALL_STATE(48)] = 1007,
  [SMALL_STATE(49)] = 1027,
  [SMALL_STATE(50)] = 1045,
  [SMALL_STATE(51)] = 1063,
  [SMALL_STATE(52)] = 1081,
  [SMALL_STATE(53)] = 1096,
  [SMALL_STATE(54)] = 1107,
  [SMALL_STATE(55)] = 1118,
  [SMALL_STATE(56)] = 1129,
  [SMALL_STATE(57)] = 1142,
  [SMALL_STATE(58)] = 1155,
  [SMALL_STATE(59)] = 1168,
  [SMALL_STATE(60)] = 1183,
  [SMALL_STATE(61)] = 1194,
  [SMALL_STATE(62)] = 1208,
  [SMALL_STATE(63)] = 1220,
  [SMALL_STATE(64)] = 1232,
  [SMALL_STATE(65)] = 1244,
  [SMALL_STATE(66)] = 1256,
  [SMALL_STATE(67)] = 1268,
  [SMALL_STATE(68)] = 1280,
  [SMALL_STATE(69)] = 1292,
  [SMALL_STATE(70)] = 1304,
  [SMALL_STATE(71)] = 1316,
  [SMALL_STATE(72)] = 1328,
  [SMALL_STATE(73)] = 1340,
  [SMALL_STATE(74)] = 1352,
  [SMALL_STATE(75)] = 1364,
  [SMALL_STATE(76)] = 1376,
  [SMALL_STATE(77)] = 1388,
  [SMALL_STATE(78)] = 1400,
  [SMALL_STATE(79)] = 1413,
  [SMALL_STATE(80)] = 1426,
  [SMALL_STATE(81)] = 1439,
  [SMALL_STATE(82)] = 1452,
  [SMALL_STATE(83)] = 1465,
  [SMALL_STATE(84)] = 1478,
  [SMALL_STATE(85)] = 1491,
  [SMALL_STATE(86)] = 1504,
  [SMALL_STATE(87)] = 1517,
  [SMALL_STATE(88)] = 1530,
  [SMALL_STATE(89)] = 1543,
  [SMALL_STATE(90)] = 1556,
  [SMALL_STATE(91)] = 1569,
  [SMALL_STATE(92)] = 1582,
  [SMALL_STATE(93)] = 1595,
  [SMALL_STATE(94)] = 1608,
  [SMALL_STATE(95)] = 1621,
  [SMALL_STATE(96)] = 1634,
  [SMALL_STATE(97)] = 1647,
  [SMALL_STATE(98)] = 1660,
  [SMALL_STATE(99)] = 1673,
  [SMALL_STATE(100)] = 1686,
  [SMALL_STATE(101)] = 1699,
  [SMALL_STATE(102)] = 1712,
  [SMALL_STATE(103)] = 1725,
  [SMALL_STATE(104)] = 1738,
  [SMALL_STATE(105)] = 1751,
  [SMALL_STATE(106)] = 1764,
  [SMALL_STATE(107)] = 1777,
  [SMALL_STATE(108)] = 1790,
  [SMALL_STATE(109)] = 1803,
  [SMALL_STATE(110)] = 1816,
  [SMALL_STATE(111)] = 1826,
  [SMALL_STATE(112)] = 1836,
  [SMALL_STATE(113)] = 1846,
  [SMALL_STATE(114)] = 1856,
  [SMALL_STATE(115)] = 1866,
  [SMALL_STATE(116)] = 1876,
  [SMALL_STATE(117)] = 1886,
  [SMALL_STATE(118)] = 1894,
  [SMALL_STATE(119)] = 1904,
  [SMALL_STATE(120)] = 1914,
  [SMALL_STATE(121)] = 1924,
  [SMALL_STATE(122)] = 1932,
  [SMALL_STATE(123)] = 1940,
  [SMALL_STATE(124)] = 1950,
  [SMALL_STATE(125)] = 1958,
  [SMALL_STATE(126)] = 1968,
  [SMALL_STATE(127)] = 1976,
  [SMALL_STATE(128)] = 1986,
  [SMALL_STATE(129)] = 1996,
  [SMALL_STATE(130)] = 2006,
  [SMALL_STATE(131)] = 2016,
  [SMALL_STATE(132)] = 2024,
  [SMALL_STATE(133)] = 2032,
  [SMALL_STATE(134)] = 2042,
  [SMALL_STATE(135)] = 2049,
  [SMALL_STATE(136)] = 2056,
  [SMALL_STATE(137)] = 2063,
  [SMALL_STATE(138)] = 2070,
  [SMALL_STATE(139)] = 2077,
  [SMALL_STATE(140)] = 2084,
  [SMALL_STATE(141)] = 2091,
  [SMALL_STATE(142)] = 2098,
  [SMALL_STATE(143)] = 2105,
  [SMALL_STATE(144)] = 2112,
  [SMALL_STATE(145)] = 2119,
  [SMALL_STATE(146)] = 2126,
  [SMALL_STATE(147)] = 2133,
  [SMALL_STATE(148)] = 2140,
  [SMALL_STATE(149)] = 2147,
  [SMALL_STATE(150)] = 2154,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(149),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [16] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(140),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(143),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_literal, 3, 0, 13),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 10),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_literal, 4, 0, 13),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_literal, 6, 0, 13),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_literal, 5, 0, 13),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_access, 3, 0, 14),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(114),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(135),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(149),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 5, 0, 2),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_enum, 5, 0, 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 3, 0, 1),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_enum, 3, 0, 1),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 1, 0, 1),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variant, 1, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_type, 1, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_ctor, 3, 0, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_path, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_path, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_path_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_module_path_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_path_repeat1, 2, 0, 0), SHIFT_REPEAT(148),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 4, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_enum, 4, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 4, 0, 2),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_enum, 4, 0, 2),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_path, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_path, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_type, 4, 0, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pointer, 4, 0, 9),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 4, 0, 5),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variant, 4, 0, 5),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_init, 3, 0, 15),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_type, 5, 0, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, 0, 1),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 5, 0, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 5, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 8, 0, 2),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 8, 0, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 6, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 6, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 8),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 8, 0, 8),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 7, 0, 1),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 7, 0, 1),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6, 0, 2),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 6, 0, 2),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 11),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 8, 0, 11),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 6, 0, 3),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 6, 0, 3),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 7),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 7, 0, 7),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 12),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 9, 0, 12),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 7, 0, 2),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 7, 0, 2),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 6),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 7, 0, 6),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6, 0, 1),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 6, 0, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_type_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_named_type_repeat1, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [285] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(128),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2, 0, 0), SHIFT_REPEAT(136),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [325] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_literal_repeat1, 2, 0, 0),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 4),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 4),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [378] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zen(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
